; Cries indexes (see audio/cry_pointers.asm)
	const_def

; gen 1
	const CRY_NIDORAN_M
	const CRY_NIDORAN_F
	const CRY_SLOWPOKE
	const CRY_KANGASKHAN
	const CRY_CHARMANDER
	const CRY_GRIMER
	const CRY_VOLTORB
	const CRY_MUK
	const CRY_ODDISH
	const CRY_RAICHU
	const CRY_NIDOQUEEN
	const CRY_DIGLETT
	const CRY_SEEL
	const CRY_DROWZEE
	const CRY_PIDGEY
	const CRY_BULBASAUR
	const CRY_SPEAROW
	const CRY_RHYDON
	const CRY_GOLEM
	const CRY_BLASTOISE
	const CRY_PIDGEOTTO
	const CRY_WEEDLE
	const CRY_CATERPIE
	const CRY_EKANS
	const CRY_FEAROW
	const CRY_CLEFAIRY
	const CRY_VENONAT
	const CRY_LAPRAS
	const CRY_METAPOD
	const CRY_SQUIRTLE
	const CRY_PARAS
	const CRY_GROWLITHE
	const CRY_KRABBY
	const CRY_PSYDUCK
	const CRY_RATTATA
	const CRY_VILEPLUME
	const CRY_VULPIX
	const CRY_WEEPINBELL

; gen 2
	const CRY_MARILL
	const CRY_SPINARAK
	const CRY_TOGEPI
	const CRY_GIRAFARIG
	const CRY_RAIKOU
	const CRY_MAREEP
	const CRY_KOLTA
	const CRY_HOOTHOOT
	const CRY_BURGELA
	const CRY_SLOWKING
	const CRY_CUBBURN
	const CRY_CHIKORITA
	const CRY_PALSSIO
	const CRY_MIMMEO
	const CRY_CLEFFA
	const CRY_COINPUR
	const CRY_LEDYBA
	const CRY_ENTEI
	const CRY_ANGORE
	const CRY_MANTINE
	const CRY_BRUINUS
	const CRY_NATU
	const CRY_QWILFISH
	const CRY_SUNFLORA
	const CRY_AMPHAROS
	const CRY_LUXWAN
	const CRY_PICHU
	const CRY_AIPOM
	const CRY_PARASPOR
	const CRY_DONPHAN
