; wEventFlags bit flags
	const_def
; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1 ; 000
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8
; Nihon Gym Leader TM gifts
	const EVENT_GOT_TM31_MUD_SLAP
	const EVENT_GOT_TM49_FURY_CUTTER
	const EVENT_GOT_TM01_DYNAMICPUNCH; used instead for Thief
	const EVENT_GOT_TM45_ATTRACT
	const EVENT_GOT_TM30_SHADOW_BALL
	const EVENT_GOT_TM23_IRON_TAIL
	const EVENT_GOT_TM16_ICY_WIND
	const EVENT_GOT_TM24_DRAGONBREATH
; HMs (EVENT_GOT_HM07_WATERFALL is with the Nihon itemballs)
	const EVENT_GOT_HM01_CUT
	const EVENT_GOT_HM02_FLY
	const EVENT_GOT_HM03_SURF
	const EVENT_GOT_HM04_STRENGTH
	const EVENT_GOT_HM05_FLASH
	const EVENT_GOT_HM06_WHIRLPOOL
	const EVENT_016
; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
	const EVENT_GOT_SUPER_ROD
; Nihon story events
	const EVENT_READ_5F1F_SIGN
	const EVENT_READ_5F2F_SIGN
	const EVENT_READ_5F3F_SIGN
	const EVENT_READ_5F4F_SIGN
	const EVENT_READ_5F5F_SIGN
	const EVENT_GOT_5F_SAGE_BLESSING
	const EVENT_GOT_A_POKEMON_FROM_OAK
	const EVENT_GOT_FLAMBEAR_FROM_OAK
	const EVENT_GOT_CRUISEAL_FROM_OAK
	const EVENT_GOT_HAPPA_FROM_OAK
	const EVENT_GOT_MYSTERY_EGG_FROM_MR_POKEMON
	const EVENT_GAVE_MYSTERY_EGG_TO_OAK2
	const EVENT_PRYCE_IN_GYM; used, for pryce in his gym
	const EVENT_CLEARED_RADIO_TOWER ;this is the end of team rocket- if this is set, they're gone
	const EVENT_CLEARED_ROCKET_HIDEOUT ;this is what's used for the end of team rocket hideout in honto(did I actually use this? Not sure)
	const EVENT_ROCKET_KEY_DIALOGUE ;used for dialogue in the rocket honto house after being told to get ship key
	const EVENT_GOT_SS_TICKET_FROM_OAK
	const EVENT_GOT_FUEL_LINE;used for getting ship fuel line 
	const EVENT_REFUSED_TO_HELP_LANCE_AT_KIKAI_VILLAGE
	const EVENT_GOT_BERRY_FROM_ROUTE_104_HOUSE
	const EVENT_TALKED_TO_ROCKET_WITH_KEY ; used for talking to the rocket who gives you the key afterwards
	const EVENT_PRYCE_IN_DEEPWATER ; used, for pryce in the deepwater passage
	const EVENT_PRYCE_IN_HOME ;used, for pryce in his house
	const EVENT_ROCKET_OUTSIDE_OF_SHIP ;used, but not for slowpoke well, for rocket outside of ship at docks
	const EVENT_REFUSED_TO_TAKE_EGG_FROM_OAKS_AIDE
	const EVENT_GOT_TOGEPI_EGG_FROM_OAKS_AIDE
	const EVENT_MADE_UNOWN_APPEAR_IN_RUINS
	const EVENT_FAST_SHIP_DESTINATION_ALLOY
	const EVENT_FAST_SHIP_FIRST_TIME
	const EVENT_FAST_SHIP_HAS_ARRIVED
	const EVENT_FAST_SHIP_FOUND_GIRL
	const EVENT_FAST_SHIP_LAZY_SAILOR
	const EVENT_FAST_SHIP_INFORMED_ABOUT_LAZY_SAILOR
	const EVENT_KURT_GAVE_YOU_LURE_BALL
	const EVENT_INITIALIZED_EVENTS
	const EVENT_GUY_GIVES_MYSTERYBERRY; used for the guy who gives you a mysteryberry in kanto cafe map
	const EVENT_KIKAI_VILLAGE_EXPLAINED_WEIRD_MAGIKARP
	const EVENT_KIKAI_VILLAGE_ASKED_FOR_MAGIKARP
	const EVENT_KIKAI_VILLAGE_ELIXIR_ON_STANDBY
	const EVENT_03B
	const EVENT_03C
	const EVENT_HEALED_MOOMOO
	const EVENT_GOT_TM13_SNORE_FROM_MOOMOO_FARM
	const EVENT_TALKED_TO_FARMER_ABOUT_MOOMOO
	const EVENT_TALKED_TO_MOM_AFTER_GETTING_POKEDEX ; 040
	const EVENT_DUDE_TALKED_TO_YOU
	const EVENT_LEARNED_TO_CATCH_POKEMON
	const EVENT_OAK2_CALLED_ABOUT_STOLEN_POKEMON
	const EVENT_BEAT_ELITE_FOUR
	const EVENT_RED_IN_KANTO_GYM; used for red appearing in the gym
	const EVENT_MANIA_TOOK_SHUCKIE_OR_LET_YOU_KEEP_HIM
	const EVENT_GOT_SUNNY_DAY_FROM_RADIO_TOWER
	const EVENT_GOT_PINK_BOW_FROM_MARY
	const EVENT_USED_BASEMENT_KEY
	const EVENT_RECEIVED_CARD_KEY
	const EVENT_GOT_TM08_ROCK_SMASH; used for the rock smash hm
	const EVENT_LANCE_HEALED_YOU_IN_TEAM_ROCKET_BASE
	const EVENT_GOT_MYSTIC_WATER_IN_CROWN
	const EVENT_GOT_TM05_ROAR
	const EVENT_GOT_EEVEE
	const EVENT_GOT_KENYA ; 050
	const EVENT_SILVER_IN_STAND_GATE; used to make silver disappear in r36 ruins gate above stand city
	const EVENT_ROCKETS_IN_STAND_CITY; makes rockets disappear in stand city not secret base
	const EVENT_GOT_TM50_NIGHTMARE; used, blue forest house 1
	const EVENT_TOGEPI_HATCHED
	const EVENT_SHOWED_TOGEPI_TO_OAK2
	const EVENT_GOT_EVERSTONE_FROM_OAK
	const EVENT_GOT_QUICK_CLAW
	const EVENT_GOT_TM10_HIDDEN_POWER
	const EVENT_GOT_TM36_SLUDGE_BOMB
	const EVENT_GOT_ITEMFINDER
	const EVENT_GOT_BICYCLE
	const EVENT_GOT_SQUIRTBOTTLE ;used for slowpoke b1f rival object
	const EVENT_GOT_MIRACLE_SEED_IN_ROUTE_112
	const EVENT_GOT_CHARCOAL_IN_BIRDON_MILK_BAR
	const EVENT_GOT_TM02_HEADBUTT
	const EVENT_DECIDED_TO_HELP_LANCE ; 060
	const EVENT_GOT_TYROGUE_FROM_KIYO
	const EVENT_MET_FRIEDA_OF_FRIDAY
	const EVENT_GOT_POISON_BARB_FROM_FRIEDA
	const EVENT_MET_TUSCANY_OF_TUESDAY
	const EVENT_GOT_PINK_BOW_FROM_TUSCANY
	const EVENT_MET_ARTHUR_OF_THURSDAY
	const EVENT_GOT_HARD_STONE_FROM_ARTHUR
	const EVENT_MET_SUNNY_OF_SUNDAY
	const EVENT_GOT_MAGNET_FROM_SUNNY
	const EVENT_MET_WESLEY_OF_WEDNESDAY
	const EVENT_GOT_BLACKBELT_FROM_WESLEY
	const EVENT_MET_SANTOS_OF_SATURDAY
	const EVENT_GOT_SPELL_TAG_FROM_SANTOS
	const EVENT_MET_MONICA_OF_MONDAY
	const EVENT_GOT_SHARP_BEAK_FROM_MONICA ; 070
	const EVENT_GOT_SOFT_SAND_FROM_KATE
	const EVENT_GOT_METAL_COAT_FROM_GRANDPA_ON_SS_AQUA; used, from ss captain after repairing ship
	const EVENT_GOT_BLACKGLASSES_IN_DARK_CAVE
	const EVENT_GOT_KINGS_ROCK_IN_SLOWPOKE_WELL
	const EVENT_GOT_TM47_STEEL_WING
	const EVENT_GOT_TM37_SANDSTORM
	const EVENT_FIRST_TIME_BANKING_WITH_MOM
	const EVENT_TOLD_OAK2_ABOUT_TOGEPI_OVER_THE_PHONE
	const EVENT_GOT_HELIX_FOSSIL
	const EVENT_GOT_DOME_FOSSIL
	const EVENT_GOT_TM12_SWEET_SCENT
	const EVENT_RELEASED_THE_BEASTS; used for 2nd rock check in new bark town /route 27
	const EVENT_GOT_MASTER_BALL_FROM_OAK
; Nihon hidden items
	const EVENT_FIVE_FLOOR_TOWER_4F_HIDDEN_MAX_POTION
	const EVENT_FIVE_FLOOR_TOWER_5F_HIDDEN_FULL_RESTORE
	const EVENT_FIVE_FLOOR_TOWER_5F_HIDDEN_CARBOS
	const EVENT_BURNED_TOWER_1F_HIDDEN_ETHER ; 080
	const EVENT_081
	const EVENT_082
	const EVENT_083
	const EVENT_NATIONAL_PARK_HIDDEN_FULL_HEAL
	const EVENT_ALLOY_LIGHTHOUSE_5F_HIDDEN_HYPER_POTION
	const EVENT_TEAM_ROCKET_BASE_OFFICE_HIDDEN_REVIVE
	const EVENT_TEAM_ROCKET_BASE_B1F_HIDDEN_FULL_HEAL
	const EVENT_JADE_FOREST_HIDDEN_ETHER
	const EVENT_JADE_FOREST_HIDDEN_SUPER_POTION
	const EVENT_JADE_FOREST_HIDDEN_FULL_HEAL
	const EVENT_WESTPORT_UNDERGROUND_HIDDEN_PARLYZ_HEAL
	const EVENT_WESTPORT_UNDERGROUND_HIDDEN_SUPER_POTION
	const EVENT_WESTPORT_UNDERGROUND_HIDDEN_ANTIDOTE
	const EVENT_WESTPORT_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_MAX_POTION
	const EVENT_WESTPORT_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_REVIVE
	const EVENT_CHARRED_SUMMIT_CAVE_HIDDEN_HYPER_POTION
	const EVENT_JOULE_CAVE_1F_HIDDEN_MAX_REPEL
	const EVENT_ICED_CAVERN_1F_HIDDEN_FULL_RESTORE
	const EVENT_ICED_CAVERN_B1F_HIDDEN_MAX_REVIVE
	const EVENT_MAGMA_SHAFT_B1F_HIDDEN_MAX_POTION
	const EVENT_MAGMA_SHAFT_B2F_HIDDEN_CARBOS
	const EVENT_MAGMA_SHAFT_1F_HIDDEN_ICE_HEAL
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_RARE_CANDY
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_FULL_RESTORE
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_DIRE_HIT
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_HIDDEN_MAX_POTION
	const EVENT_AMPARE_CAVERN_B1F_HIDDEN_ELIXER
	const EVENT_VICTORY_ROAD_HIDDEN_MAX_POTION
	const EVENT_VICTORY_ROAD_HIDDEN_FULL_HEAL
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_REVIVE
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_POTION
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_ELIXER
	const EVENT_ROUTE_U5U_HIDDEN_RARE_CANDY
	const EVENT_ROUTE_105_HIDDEN_POTION
	const EVENT_ROUTE_112_HIDDEN_GREAT_BALL
	const EVENT_ROUTE_112_HIDDEN_SUPER_POTION
	const EVENT_ROUTE_113_HIDDEN_RARE_CANDY
	const EVENT_ROUTE_113_HIDDEN_SUPER_POTION
	const EVENT_SILENT_HILLS_HIDDEN_ETHER
	const EVENT_ROUTE_109_HIDDEN_NUGGET
	const EVENT_ROUTE_110_HIDDEN_HYPER_POTION
	const EVENT_ROUTE_111_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_U4U_HIDDEN_MAX_POTION
	const EVENT_KIKAI_STRAIT_HIDDEN_ELIXER
	const EVENT_VICTORY_ROAD_2F_HIDDEN_PP_UP; victory road 2f tm toxic
	const EVENT_PAGOTA_CITY_HIDDEN_HYPER_POTION
	const EVENT_BIRDON_TOWN_HIDDEN_FULL_HEAL
	const EVENT_SUNPOINT_CITY_HIDDEN_REVIVE
	const EVENT_SUNPOINT_CITY_HIDDEN_MAX_ETHER
	const EVENT_TEKNOS_CITY_HIDDEN_HYPER_POTION
	const EVENT_KIKAI_VILLAGE_HIDDEN_FULL_RESTORE
	const EVENT_KIKAI_VILLAGE_HIDDEN_RARE_CANDY
	const EVENT_KIKAI_VILLAGE_HIDDEN_MAX_POTION
	const EVENT_DAITO_RANCH_HIDDEN_FULL_RESTORE
; Crystal-exclusive events in Nihon
	const EVENT_MET_FLORIA
	const EVENT_TALKED_TO_FLORIA_AT_FLOWER_SHOP
	const EVENT_BUGGING_KURT_TOO_MUCH
	const EVENT_TALKED_TO_RUINS_COWARD
	const EVENT_GOT_DRATINI; used for clair giving dratini
	const EVENT_CAN_GIVE_GS_BALL_TO_KURT
	const EVENT_GAVE_GS_BALL_TO_KURT
	const EVENT_FOREST_IS_RESTLESS
	const EVENT_ANSWERED_DRAGON_MASTER_QUIZ_WRONG
	const EVENT_IEJIMA_TOWN_FIXED
	const EVENT_DAM_IS_OPEN
	const EVENT_0C4
	const EVENT_0C5
	const EVENT_0C6
	const EVENT_0C7
; SWIslands story events
	const EVENT_GOT_NUGGET_FROM_GUY
	const EVENT_RETURNED_MACHINE_PART; used, for returning dragon orb
	const EVENT_MET_MANAGER_AT_HYDRO_PLANT
	const EVENT_MET_ROCKET_GRUNT_AT_JADE_FOREST_SNORLAX_ROOM
	const EVENT_MET_REDS_MOM
	const EVENT_RESTORED_POWER_TO_SWISLANDS
	const EVENT_GOT_COINS_FROM_GAMBLER_AT_KANTO
	const EVENT_MET_COPYCAT_FOUND_OUT_ABOUT_LOST_ITEM
	const EVENT_RETURNED_LOST_ITEM_TO_COPYCAT
	const EVENT_GOT_PASS_FROM_COPYCAT; battle pass for swislands trainer club
	const EVENT_GOT_LOST_ITEM_FROM_FAN_CLUB
	const EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT_BUT_BAG_WAS_FULL
	const EVENT_LISTENED_TO_FAN_CLUB_PRESIDENT
	const EVENT_TALKED_TO_SEAFOAM_GYM_GUY_ONCE
	const EVENT_ENABLE_DIPLOMA_PRINTING
	const EVENT_FROSTPOINT_ROCKS_CLEARED
	const EVENT_CLEARED_NUGGET_BRIDGE
	const EVENT_TALKED_TO_WARDENS_GRANDDAUGHTER
	const EVENT_GOT_TM03_CURSE
	const EVENT_GOT_CLEANSE_TAG
	const EVENT_GOT_TM19_GIGA_DRAIN; unused, was in kanto gym
	const EVENT_GOT_TM06_TOXIC
	const EVENT_GOT_UP_GRADE
	const EVENT_GOT_TM07_ZAP_CANNON
	const EVENT_GOT_TM42_DREAM_EATER
	const EVENT_TALKED_TO_OAK_IN_SWISLANDS
	const EVENT_GOT_HP_UP_FROM_AMAMI_GUY
	const EVENT_GOT_TM29_PSYCHIC
; SWIslands hidden items
	const EVENT_ENDON_CAVE_1F_HIDDEN_MAX_REVIVE
	const EVENT_CROWN_PATH_HIDDEN_FULL_RESTORE
	const EVENT_CROWN_PATH_HIDDEN_X_SPECIAL
	const EVENT_BOULDER_MINE_B2F_HIDDEN_X_ACCURACY
	const EVENT_BOULDER_MINE_B2F_HIDDEN_STEEL_SHELL
	const EVENT_BOULDER_MINE_B3F_HIDDEN_MAX_POTION
	const EVENT_WESTPORT_PORT_HIDDEN_PROTEIN
	const EVENT_AMAMI_PORT_HIDDEN_IRON
	const EVENT_MOUNT_FUJI_OUTSIDE_HIDDEN_MOON_STONE
	const EVENT_ROUTE_116_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_116_HIDDEN_FULL_HEAL
	const EVENT_ROUTE_116_HIDDEN_FULL_RESTORE
	const EVENT_ROUTE_116_HIDDEN_REVIVE
	const EVENT_ROUTE_118_HIDDEN_ULTRA_BALL
	const EVENT_ROUTE_114_HIDDEN_ETHER
	const EVENT_URASOE_TRAIL_HIDDEN_ELIXER
	const EVENT_ROUTE_U12U_HIDDEN_CALCIUM
	const EVENT_MOTOBU_PATH_HIDDEN_REVIVE
	const EVENT_WEATHERED_TRAIL_HIDDEN_MAX_ETHER
	const EVENT_WEATHERED_TRAIL_HIDDEN_MAX_ELIXER
	const EVENT_MERIDIAN_PATH_HIDDEN_POTION
	const EVENT_FOUND_LEFTOVERS_IN_KANTO_CAFE
	const EVENT_FOUND_BERSERK_GENE_IN_NAGO_VILLAGE
	const EVENT_FOUND_MACHINE_PART_IN_JADE_FOREST_SNORLAX_ROOM; used, for getting dragon orb
	const EVENT_AMAMI_TOWN_HIDDEN_FULL_HEAL
	const EVENT_KANTO_REGION_HIDDEN_PP_UP
	const EVENT_FROSTPOINT_TOWN_HIDDEN_RARE_CANDY
	const EVENT_BURNED_TOWER_1F_HIDDEN_ULTRA_BALL
	const EVENT_GINA_GAVE_LEAF_STONE
	const EVENT_ALAN_GAVE_FIRE_STONE
	const EVENT_DANA_GAVE_THUNDERSTONE
	const EVENT_TULLY_GAVE_WATER_STONE
	const EVENT_TIFFANY_GAVE_PINK_BOW
; ???
	const EVENT_251
	const EVENT_252
	const EVENT_253
	const EVENT_254
	const EVENT_255
	const EVENT_256
	const EVENT_257
; Kurt Apricorn events
	const EVENT_GAVE_KURT_RED_APRICORN
	const EVENT_GAVE_KURT_BLU_APRICORN
	const EVENT_GAVE_KURT_YLW_APRICORN
	const EVENT_GAVE_KURT_GRN_APRICORN
	const EVENT_GAVE_KURT_WHT_APRICORN
	const EVENT_GAVE_KURT_BLK_APRICORN
	const EVENT_GAVE_KURT_PNK_APRICORN
; Phone events
	const EVENT_JACK_ASKED_FOR_PHONE_NUMBER
	const EVENT_260
	const EVENT_BEVERLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_262
	const EVENT_HUEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_264
	const EVENT_GOT_PROTEIN_FROM_HUEY
	const EVENT_GOT_HP_UP_FROM_JOEY
	const EVENT_GOT_CARBOS_FROM_VANCE
	const EVENT_GOT_IRON_FROM_PARRY
	const EVENT_GOT_CALCIUM_FROM_ERIN
	const EVENT_KENJI_ON_BREAK
	const EVENT_GAVEN_ASKED_FOR_PHONE_NUMBER
	const EVENT_26C
	const EVENT_BETH_ASKED_FOR_PHONE_NUMBER
	const EVENT_26E
	const EVENT_JOSE_ASKED_FOR_PHONE_NUMBER
	const EVENT_270
	const EVENT_REENA_ASKED_FOR_PHONE_NUMBER
	const EVENT_272
	const EVENT_JOEY_ASKED_FOR_PHONE_NUMBER
	const EVENT_274
	const EVENT_WADE_ASKED_FOR_PHONE_NUMBER
	const EVENT_276
	const EVENT_RALPH_ASKED_FOR_PHONE_NUMBER
	const EVENT_278
	const EVENT_LIZ_ASKED_FOR_PHONE_NUMBER
	const EVENT_27A
	const EVENT_ANTHONY_ASKED_FOR_PHONE_NUMBER
	const EVENT_27C
	const EVENT_TODD_ASKED_FOR_PHONE_NUMBER
	const EVENT_27E
	const EVENT_GINA_ASKED_FOR_PHONE_NUMBER
	const EVENT_280 ; 280
	const EVENT_IRWIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_282
	const EVENT_ARNIE_ASKED_FOR_PHONE_NUMBER
	const EVENT_284
	const EVENT_ALAN_ASKED_FOR_PHONE_NUMBER
	const EVENT_286
	const EVENT_287
	const EVENT_288
	const EVENT_DANA_ASKED_FOR_PHONE_NUMBER
	const EVENT_28A
	const EVENT_CHAD_ASKED_FOR_PHONE_NUMBER
	const EVENT_28C
	const EVENT_DEREK_ASKED_FOR_PHONE_NUMBER
	const EVENT_28E
	const EVENT_TULLY_ASKED_FOR_PHONE_NUMBER
	const EVENT_290 ; 290
	const EVENT_BRENT_ASKED_FOR_PHONE_NUMBER
	const EVENT_292
	const EVENT_TIFFANY_ASKED_FOR_PHONE_NUMBER
	const EVENT_294
	const EVENT_VANCE_ASKED_FOR_PHONE_NUMBER
	const EVENT_296
	const EVENT_WILTON_ASKED_FOR_PHONE_NUMBER
	const EVENT_298
	const EVENT_KENJI_ASKED_FOR_PHONE_NUMBER
	const EVENT_29A
	const EVENT_PARRY_ASKED_FOR_PHONE_NUMBER
	const EVENT_29C
	const EVENT_ERIN_ASKED_FOR_PHONE_NUMBER
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER_NO_BLUE_CARD
	const EVENT_29F
; Ruins of Alph puzzles
	const EVENT_SOLVED_HO_OH_PUZZLE ; 2a0
	const EVENT_SOLVED_KABUTO_PUZZLE
	const EVENT_SOLVED_OMANYTE_PUZZLE
	const EVENT_SOLVED_AERODACTYL_PUZZLE
; Decorations
	const EVENT_DECO_BED_1; at start of game?
	const EVENT_DECO_BED_2; boardwalk game corner
	const EVENT_DECO_BED_3; boardwalk game corner
	const EVENT_DECO_BED_4; boardwalk game corner
	const EVENT_DECO_CARPET_1; at start of game?
	const EVENT_DECO_CARPET_2; boardwalk 
	const EVENT_DECO_CARPET_3; boardwalk
	const EVENT_DECO_CARPET_4; boardwalk
	const EVENT_DECO_PLANT_1; boardwalk
	const EVENT_DECO_PLANT_2; boardwalk
	const EVENT_DECO_PLANT_3; boardwalk
	const EVENT_DECO_PLANT_4; unused?
	const EVENT_DECO_POSTER_1 ; at start of game
	const EVENT_DECO_POSTER_2; kanto
	const EVENT_DECO_POSTER_3; kanto
	const EVENT_DECO_FAMICOM; kanto
	const EVENT_DECO_SNES; kanto
	const EVENT_DECO_N64; at start of game
	const EVENT_DECO_VIRTUAL_BOY; kanto
	const EVENT_DECO_PIKACHU_DOLL; mom
	const EVENT_DECO_SURFING_PIKACHU_DOLL; travel 1
	const EVENT_DECO_CLEFAIRY_DOLL; mom
	const EVENT_DECO_JIGGLYPUFF_DOLL; travel 1
	const EVENT_DECO_BULBASAUR_DOLL; travel 1
	const EVENT_DECO_CHARMANDER_DOLL; travel 2
	const EVENT_DECO_SQUIRTLE_DOLL; travel 3
	const EVENT_DECO_POLIWAG_DOLL; mom
	const EVENT_DECO_DIGLETT_DOLL; travel 2
	const EVENT_DECO_STARMIE_DOLL; travel 2
	const EVENT_DECO_MAGIKARP_DOLL; travel 3
	const EVENT_DECO_ODDISH_DOLL; travel 3
	const EVENT_DECO_GENGAR_DOLL; travel 4
	const EVENT_DECO_SHELLDER_DOLL; travel 4
	const EVENT_DECO_GRIMER_DOLL; travel 4
	const EVENT_DECO_VOLTORB_DOLL; travel 5
	const EVENT_DECO_WEEDLE_DOLL; travel 5
	const EVENT_DECO_UNOWN_DOLL; from completing unown dex
	const EVENT_DECO_GEODUDE_DOLL; travel 5
	const EVENT_DECO_MACHOP_DOLL; travel 6
	const EVENT_DECO_TENTACOOL_DOLL; travel 6
	const EVENT_PLAYERS_ROOM_POSTER; not needed?
	const EVENT_DECO_GOLD_TROPHY; beat elite 4
	const EVENT_DECO_SILVER_TROPHY; blue trophy; added, get from beating blue
	const EVENT_DECO_BIG_SNORLAX_DOLL; mom
	const EVENT_DECO_BIG_ONIX_DOLL ; kanto
	const EVENT_DECO_BIG_LAPRAS_DOLL; kanto
; More Nihon story events
	const EVENT_WARPED_FROM_ROUTE_103_NATIONAL_PARK_GATE
	const EVENT_SWITCH_1; sunday
	const EVENT_SWITCH_2; monday
	const EVENT_SWITCH_3; tueaday
	const EVENT_EMERGENCY_SWITCH; used, makes rival disappear in princely path / underground
	const EVENT_SWITCH_4; wednesday
	const EVENT_SWITCH_5; thursday
	const EVENT_SWITCH_6; friday
	const EVENT_SWITCH_7; saturday
	const EVENT_SWITCH_8; determining if bouncer gave you item
	const EVENT_SWITCH_9; used after talking to heal lass on mt fuji for the first time
	const EVENT_SWITCH_10; scope lens from granny in prince city
	const EVENT_SWITCH_11; used for mewtwo
	const EVENT_SWITCH_12; used for getting starter 2 in kume city/kume city
	const EVENT_SWITCH_13 ; 2e0
	const EVENT_SWITCH_14; event set after getting dratini
	const EVENT_UNCOVERED_STAIRCASE_IN_OLD_MAHOGANY_MART
	const EVENT_TURNED_OFF_SECURITY_CAMERAS
	const EVENT_SECURITY_CAMERA_1
	const EVENT_SECURITY_CAMERA_2
	const EVENT_SECURITY_CAMERA_3
	const EVENT_SECURITY_CAMERA_4
	const EVENT_SECURITY_CAMERA_5
	const EVENT_EXPLODING_TRAP_1; used for old man abra warp at amami town
	const EVENT_EXPLODING_TRAP_2;  used for old man abra warp at west city
	const EVENT_EXPLODING_TRAP_3; used for zapdos encounter
	const EVENT_EXPLODING_TRAP_4; used for moltres encounter
	const EVENT_GOT_SKATEBOARD; used for getting skateboard
	const EVENT_EXPLODING_TRAP_6; used for getting charmander in nago village
	const EVENT_EXPLODING_TRAP_7; used for moltres appear/disappear
	const EVENT_EXPLODING_TRAP_8 ; used for zapdos appear/disappear
	const EVENT_EXPLODING_TRAP_9; articuno event
	const EVENT_EXPLODING_TRAP_10; used for making articuno appear/disappear
	const EVENT_EXPLODING_TRAP_11; used for tri wing youngster in forest
	const EVENT_EXPLODING_TRAP_12; used for him as well, but for after giving wing
	const EVENT_EXPLODING_TRAP_13; used for getting squirtle in amami town
	const EVENT_EXPLODING_TRAP_14; used for getting bulbasaur in ryukyu city
	const EVENT_EXPLODING_TRAP_15; used for silver in safari zone beta
	const EVENT_EXPLODING_TRAP_16; used also for silver in safari zone beta
	const EVENT_EXPLODING_TRAP_17; used for mew
	const EVENT_EXPLODING_TRAP_18; also for mew
	const EVENT_EXPLODING_TRAP_19; used for type gym leader
	const EVENT_EXPLODING_TRAP_20; used for fake gym egg
	const EVENT_EXPLODING_TRAP_21; used for slowpoke well kings rock guy
	const EVENT_EXPLODING_TRAP_22; used for getting togepi from youngster in battle club
	const EVENT_LEARNED_HAIL_GIOVANNI
	const EVENT_OPENED_DOOR_TO_ROCKET_HIDEOUT_TRANSMITTER ; 300
	const EVENT_LEARNED_SLOWPOKETAIL
	const EVENT_LEARNED_RATICATE_TAIL
	const EVENT_OPENED_DOOR_TO_GIOVANNIS_OFFICE
	const EVENT_WESTPORT_DEPT_STORE_B1F_LAYOUT_1; used to make rocker appear in game corner
	const EVENT_WESTPORT_DEPT_STORE_B1F_LAYOUT_2; used to make rocker appear in n64 house
	const EVENT_WESTPORT_DEPT_STORE_B1F_LAYOUT_3; used to make lass appear in kume building
	const EVENT_WESTPORT_UNDERGROUND_WAREHOUSE_BLOCKED_OFF; used to make lass appear in n64 house
	const EVENT_LEFT_MONS_WITH_CONTEST_OFFICER
	const EVENT_WILLS_ROOM_ENTRANCE_CLOSED
	const EVENT_WILLS_ROOM_EXIT_OPEN
	const EVENT_KOGAS_ROOM_ENTRANCE_CLOSED
	const EVENT_KOGAS_ROOM_EXIT_OPEN
	const EVENT_BRUNOS_ROOM_ENTRANCE_CLOSED
	const EVENT_BRUNOS_ROOM_EXIT_OPEN
	const EVENT_KARENS_ROOM_ENTRANCE_CLOSED
	const EVENT_KARENS_ROOM_EXIT_OPEN ; 310
	const EVENT_LANCES_ROOM_ENTRANCE_CLOSED
	const EVENT_LANCES_ROOM_EXIT_OPEN
	const EVENT_CONTEST_OFFICER_HAS_HEART_STONE
	const EVENT_CONTEST_OFFICER_HAS_EVERSTONE
	const EVENT_CONTEST_OFFICER_HAS_GOLD_BERRY
	const EVENT_CONTEST_OFFICER_HAS_BERRY
	const EVENT_FOUGHT_HO_OH
	const EVENT_FOUGHT_BLISSEY
	const EVENT_BEAT_RIVAL_IN_MT_MOON
	const EVENT_MET_BILLS_GRANDPA
	const EVENT_SHOWED_LICKITUNG_TO_BILLS_GRANDPA
	const EVENT_SHOWED_ODDISH_TO_BILLS_GRANDPA
	const EVENT_SHOWED_STARYU_TO_BILLS_GRANDPA
	const EVENT_SHOWED_GROWLITHE_VULPIX_TO_BILLS_GRANDPA
	const EVENT_SHOWED_PICHU_TO_BILLS_GRANDPA
	const EVENT_GOT_EVERSTONE_FROM_BILLS_GRANDPA ; 320
	const EVENT_GOT_LEAF_STONE_FROM_BILLS_GRANDPA; used to make youngster disappear from over world and go to...
	const EVENT_GOT_WATER_STONE_FROM_BILLS_GRANDPA; ...the n64 house, this makes him appear
	const EVENT_GOT_FIRE_STONE_FROM_BILLS_GRANDPA; used to trigger the search for n64 trainers
	const EVENT_GOT_THUNDERSTONE_FROM_BILLS_GRANDPA
	const EVENT_LISTENED_TO_INITIAL_RADIO
; More Crystal-exclusive events in Nihon
	const EVENT_WALL_OPENED_IN_HO_OH_CHAMBER
	const EVENT_WALL_OPENED_IN_KABUTO_CHAMBER
	const EVENT_WALL_OPENED_IN_OMANYTE_CHAMBER
	const EVENT_WALL_OPENED_IN_AERODACTYL_CHAMBER
	const EVENT_WELCOMED_TO_POKECOM_CENTER
	const EVENT_WADE_HAS_BERRY
	const EVENT_WADE_HAS_PSNCUREBERRY
	const EVENT_WADE_HAS_PRZCUREBERRY
	const EVENT_WADE_HAS_BITTER_BERRY
	const EVENT_WILTON_HAS_ULTRA_BALL
	const EVENT_WILTON_HAS_GREAT_BALL
	const EVENT_WILTON_HAS_POKE_BALL
	const EVENT_HOLE_IN_BURNED_TOWER
	const EVENT_FOUGHT_EUSINE
	const EVENT_KOJI_ALLOWS_YOU_PASSAGE_TO_TIN_TOWER
	const EVENT_FOUGHT_SUICUNE
	const EVENT_GOT_RAINBOW_WING
	const EVENT_HUEY_PROTEIN
	const EVENT_JOEY_HP_UP
	const EVENT_VANCE_CARBOS
	const EVENT_PARRY_IRON
	const EVENT_ERIN_CALCIUM
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER
	const EVENT_MET_BUENA
	const EVENT_GOT_ODD_EGG
	const EVENT_33F
	const EVENT_GOT_GS_BALL_FROM_POKECOM_CENTER
; ???
	const EVENT_DONE_FS_GATE_CHECK
	const EVENT_BEAT_BLACKBELT_TARO
	const EVENT_MEW_SPOT_2_FOUND ; islands events initializing
	const EVENT_MEW_SPOT_3_FOUND
	const EVENT_MEW_SPOT_4_FOUND
	const EVENT_MEW_SPOT_5_FOUND
	const EVENT_MEW_SPOT_6_FOUND
	const EVENT_MEW_SPOT_7_FOUND
	const EVENT_MEW_SPOT_8_FOUND
	const EVENT_INIT_RIC_OBJECTS_HIDDEN
	const EVENT_RIC_BLUE_HIDDEN
	const EVENT_RI_BLUEBATTLE_HIDDEN
	const EVENT_TATSUGO_PATH_ITEMBALL
	const EVENT_BEAT_SUPER_NERD_NORTON
	const EVENT_BEAT_TEACHER_HOLLY
	const EVENT_BEAT_INSTRUCTOR_MOSHE
	const EVENT_KIKAI_SUMMIT_OTHER_ROCK
	const EVENT_BRUNO_SMASHED_ROCK
	const EVENT_KIKAI_SUMMIT_ITEMBALL
	const EVENT_BRUNO_BATTLE_DONE
	const EVENT_MEW_SPOT_1_FOUND
	const EVENT_BEAT_BLACKBELT_TAKESHIKKC
	const EVENT_BEAT_BLACKBELT_IZO
	const EVENT_KKC1_ITEMBALL1
	const EVENT_KKC1_ITEMBALL2
	const EVENT_BEAT_BLACKBELT_OKUMA
	const EVENT_KKC2_ITEMBALL
	const EVENT_GES_NUGGET
	const EVENT_MEW_FOUGHT
	const EVENT_SLOWKING_HINT_2
	const EVENT_SLOWKING_HINT_3
	const EVENT_SLOWKING_HINT_4
	const EVENT_SLOWKING_HINT_5
	const EVENT_SLOWKING_HINT_6
	const EVENT_SLOWKING_HINT_7
	const EVENT_SLOWKING_HINT_8
	const EVENT_GOT_BERRY_JUICE_FROM_GEOFF
	const EVENT_DAITO_HIDDENBERRY1
	const EVENT_DAITO_HIDDENBERRY2
	const EVENT_DAITO_HIDDENBERRY3
	const EVENT_DAITO_HIDDENBERRY4
	const EVENT_GEOFFREY_GONE_TO_DAITO
	const EVENT_BLUE_ON_RAINBOW_ISLAND
	const EVENT_BEAT_FS_STIRNER
	const EVENT_BEAT_FS_DALTON
	const EVENT_FS_LUREBALL_ITEM
	const EVENT_BEAT_BIKER_BLAZE
	const EVENT_BEAT_BIKER_RAFAEL
	const EVENT_BEAT_BIKER_COLTON
	const EVENT_BEAT_BIKER_JERMAINE
	const EVENT_IEJIMA_TOWN_NOT_FIXED
	const EVENT_IEJIMA_TOWN_TRI_WING
	const EVENT_ROCKETS_BLOCKING_AQUARIUM
	const EVENT_WHITNEY_FIGHTING_ROCKETS
	const EVENT_AQUARIUM_ROCKETS_IDLE
	const EVENT_WHITNEY_1_AQUARIUM
	const EVENT_WHITNEY_2_AQUARIUM
	const EVENT_ELDER_IN_WELL
	const EVENT_GOT_OLD_AMBER_FROM_FARMER
	const EVENT_TATSUGO_PATH_HIDDEN_PP_UP
	const EVENT_WEATHERED_TRAIL_HIDDEN_RARE_CANDY
	const EVENT_WEATHERED_TRAIL_HIDDEN_ENERGY_WALL
	const EVENT_REMATCH_AVAILABLE_OKERA
	const EVENT_REMATCH_AVAILABLE_FALKNER
	const EVENT_REMATCH_AVAILABLE_BUGSY
	const EVENT_REMATCH_AVAILABLE_WHITNEY
	const EVENT_REMATCH_AVAILABLE_MORTY
	const EVENT_REMATCH_AVAILABLE_JASMINE
	const EVENT_REMATCH_AVAILABLE_PRYCE
	const EVENT_REMATCH_AVAILABLE_RED
	const EVENT_MOTOBU_PATH_ITEMBALL
	const EVENT_URASOE_PARK_CALM_SEED
	const EVENT_ISEN_LAB_LONG_TONGUE
	const EVENT_PAGOTA_CITY_STIMULUS_ORB
	const EVENT_OKERA_NOT_IN_GYM
	const EVENT_OKERA_OWES_YOU_ONE
	const EVENT_HYDRO_PLANT_NUGGET
	const EVENT_GOT_ITEM_FROM_IEJIMA_GRAMPS
	const EVENT_BEAT_BIKER_SWANSON
	const EVENT_SWANSON_IS_GONE
	const EVENT_BEAT_COOLTRAINERM_LIAM
	const EVENT_TALKED_TO_MOM_AT_BEGINNING
	const EVENT_TALKED_TO_OUTSIDE_SCIENTIST
	const EVENT_GOT_UNOWN_DOLL_FROM_SCIENTIST
	const EVENT_DOLL_SALESMAN_MONDAY
	const EVENT_DOLL_SALESMAN_TUESDAY
	const EVENT_DOLL_SALESMAN_WEDNESDAY
	const EVENT_DOLL_SALESMAN_THURSDAY
	const EVENT_DOLL_SALESMAN_FRIDAY
	const EVENT_DOLL_SALESMAN_SATURDAY
	const EVENT_SCIENTIST_SEQUENCE
	const EVENT_BEAT_SAGE_YUREI
	const EVENT_ISEN_LAB_COVENANT_ORB
	const EVENT_38E
	const EVENT_38F
	const EVENT_390
	const EVENT_391
	const EVENT_392
	const EVENT_393
	const EVENT_394
	const EVENT_395
	const EVENT_396
	const EVENT_397
	const EVENT_398
	const EVENT_399
	const EVENT_39A
	const EVENT_39B
	const EVENT_39C
	const EVENT_39D
	const EVENT_39E
	const EVENT_39F
	const EVENT_3A0
	const EVENT_3A1
	const EVENT_3A2
	const EVENT_3A3
	const EVENT_3A4
	const EVENT_3A5
	const EVENT_3A6
	const EVENT_3A7
	const EVENT_3A8
	const EVENT_3A9
	const EVENT_3AA
	const EVENT_3AB
	const EVENT_3AC
	const EVENT_3AD
	const EVENT_3AE
	const EVENT_3AF
	const EVENT_3B0
	const EVENT_3B1
	const EVENT_3B2
	const EVENT_3B3
	const EVENT_3B4
	const EVENT_3B5
	const EVENT_3B6
	const EVENT_3B7
	const EVENT_3B8
	const EVENT_3B9
	const EVENT_3BA
	const EVENT_3BB
	const EVENT_3BC
	const EVENT_3BD
	const EVENT_3BE
	const EVENT_3BF
	const EVENT_3C0
	const EVENT_3C1
	const EVENT_3C2
	const EVENT_3C3
	const EVENT_3C4
	const EVENT_3C5
	const EVENT_3C6
	const EVENT_3C7
	const EVENT_3C8
	const EVENT_3C9
	const EVENT_3CA
	const EVENT_3CB
	const EVENT_3CC
	const EVENT_3CD
	const EVENT_3CE
	const EVENT_3CF
	const EVENT_3D0
	const EVENT_3D1
	const EVENT_3D2
	const EVENT_3E3
	const EVENT_3E4
	const EVENT_3E5
	const EVENT_3E6
	const EVENT_3E7
; Trainer flags
; Swimmer F
	const EVENT_BEAT_SWIMMERF_ELAINE
	const EVENT_BEAT_SWIMMERF_PAULA
	const EVENT_BEAT_SWIMMERF_KAYLEE
	const EVENT_BEAT_SWIMMERF_SUSIE
	const EVENT_BEAT_SWIMMERF_DENISE
	const EVENT_BEAT_SWIMMERF_KARA
	const EVENT_BEAT_SWIMMERF_WENDY
	const EVENT_BEAT_SWIMMERF_LISA
	const EVENT_BEAT_SWIMMERF_JILL
	const EVENT_BEAT_SWIMMERF_MARY
	const EVENT_BEAT_SWIMMERF_KATIE
	const EVENT_BEAT_SWIMMERF_DAWN
	const EVENT_BEAT_SWIMMERF_TARA
	const EVENT_BEAT_SWIMMERF_NICOLE
	const EVENT_BEAT_SWIMMERF_LORI
	const EVENT_BEAT_SWIMMERF_JODY
	const EVENT_BEAT_SWIMMERF_NIKKI
	const EVENT_BEAT_SWIMMERF_DIANA
	const EVENT_BEAT_SWIMMERF_BRIANA
; Bird Keeper
	const EVENT_BEAT_BIRD_KEEPER_ROD
	const EVENT_BEAT_BIRD_KEEPER_ABE
	const EVENT_BEAT_BIRD_KEEPER_BRYAN
	const EVENT_BEAT_BIRD_KEEPER_THEO
	const EVENT_BEAT_BIRD_KEEPER_TOBY
	const EVENT_BEAT_BIRD_KEEPER_DENIS
	const EVENT_BEAT_BIRD_KEEPER_VANCE
	const EVENT_BEAT_BIRD_KEEPER_HANK
	const EVENT_BEAT_BIRD_KEEPER_ROY
	const EVENT_BEAT_BIRD_KEEPER_BORIS
	const EVENT_BEAT_BIRD_KEEPER_BOB
	const EVENT_BEAT_BIRD_KEEPER_JOSE
	const EVENT_BEAT_BIRD_KEEPER_PETER
	const EVENT_BEAT_BIRD_KEEPER_JOSE2
	const EVENT_BEAT_BIRD_KEEPER_PERRY
	const EVENT_BEAT_BIRD_KEEPER_BRET
	const EVENT_BEAT_BIRD_KEEPER_JOSE3
	const EVENT_BEAT_BIRD_KEEPER_VANCE2
	const EVENT_BEAT_BIRD_KEEPER_VANCE3
; Boarder
	const EVENT_BEAT_BOARDER_RONALD
	const EVENT_BEAT_BOARDER_BRAD
	const EVENT_BEAT_BOARDER_DOUGLAS
; Sage
	const EVENT_BEAT_SAGE_CHOW
	const EVENT_BEAT_SAGE_NICO
	const EVENT_BEAT_SAGE_JIN
	const EVENT_BEAT_SAGE_TROY
	const EVENT_BEAT_SAGE_JEFFREY
	const EVENT_BEAT_SAGE_PING
	const EVENT_BEAT_SAGE_EDMOND
	const EVENT_BEAT_SAGE_NEAL
	const EVENT_BEAT_SAGE_LI
; Camper
	const EVENT_BEAT_CAMPER_ROLAND
	const EVENT_BEAT_CAMPER_TODD
	const EVENT_BEAT_CAMPER_IVAN
	const EVENT_BEAT_CAMPER_ELLIOT
	const EVENT_BEAT_CAMPER_BARRY
	const EVENT_BEAT_CAMPER_LLOYD
	const EVENT_BEAT_CAMPER_DEAN
	const EVENT_BEAT_CAMPER_SID
	const EVENT_BEAT_CAMPER_HERVEY
	const EVENT_BEAT_CAMPER_DALE
	const EVENT_BEAT_CAMPER_TED
	const EVENT_BEAT_CAMPER_TODD2
	const EVENT_BEAT_CAMPER_TODD3
	const EVENT_BEAT_CAMPER_THOMAS
	const EVENT_BEAT_CAMPER_LEROY
	const EVENT_BEAT_CAMPER_DAVID
	const EVENT_BEAT_CAMPER_JOHN
	const EVENT_BEAT_CAMPER_JERRY
	const EVENT_BEAT_CAMPER_SPENCER
; Burglar
	const EVENT_BEAT_BURGLAR_DUNCAN
	const EVENT_BEAT_BURGLAR_EDDIE
	const EVENT_BEAT_BURGLAR_COREY
; Unknown
	const EVENT_430
; Biker
	const EVENT_BEAT_BIKER_BENNY
	const EVENT_BEAT_BIKER_KAZU
	const EVENT_BEAT_BIKER_DWAYNE
	const EVENT_BEAT_BIKER_HARRIS
	const EVENT_BEAT_BIKER_ZEKE
	const EVENT_BEAT_BIKER_CHARLES
	const EVENT_BEAT_BIKER_RILEY
	const EVENT_BEAT_BIKER_JOEL
	const EVENT_BEAT_BIKER_GLENN
; Psychic
	const EVENT_BEAT_PSYCHIC_NATHAN
	const EVENT_BEAT_PSYCHIC_FRANKLIN
	const EVENT_BEAT_PSYCHIC_HERMAN
	const EVENT_BEAT_PSYCHIC_FIDEL
	const EVENT_BEAT_PSYCHIC_GREG
	const EVENT_BEAT_PSYCHIC_NORMAN
	const EVENT_BEAT_PSYCHIC_MARK
	const EVENT_BEAT_PSYCHIC_PHIL
	const EVENT_BEAT_PSYCHIC_RICHARD
	const EVENT_BEAT_PSYCHIC_GILBERT
	const EVENT_BEAT_PSYCHIC_JARED
	const EVENT_BEAT_PSYCHIC_RODNEY
; Firebreather
	const EVENT_BEAT_FIREBREATHER_OTIS
	const EVENT_BEAT_FIREBREATHER_DICK
	const EVENT_BEAT_FIREBREATHER_NED
	const EVENT_BEAT_FIREBREATHER_BURT
	const EVENT_BEAT_FIREBREATHER_BILL
	const EVENT_BEAT_FIREBREATHER_WALT
	const EVENT_BEAT_FIREBREATHER_RAY
	const EVENT_BEAT_FIREBREATHER_LYLE
; Fisher
	const EVENT_BEAT_FISHER_JUSTIN
	const EVENT_BEAT_FISHER_RALPH
	const EVENT_BEAT_FISHER_ARNOLD
	const EVENT_BEAT_FISHER_KYLE
	const EVENT_BEAT_FISHER_HENRY
	const EVENT_BEAT_FISHER_MARVIN
	const EVENT_BEAT_FISHER_TULLY
	const EVENT_BEAT_FISHER_ANDRE
	const EVENT_BEAT_FISHER_RAYMOND
	const EVENT_BEAT_FISHER_WILTON
	const EVENT_BEAT_FISHER_EDGAR
	const EVENT_BEAT_FISHER_JONAH
	const EVENT_BEAT_FISHER_MARTIN
	const EVENT_BEAT_FISHER_STEPHEN
	const EVENT_BEAT_FISHER_BARNEY
	const EVENT_BEAT_FISHER_RALPH2
	const EVENT_BEAT_FISHER_RALPH3
	const EVENT_BEAT_FISHER_TULLY2
	const EVENT_BEAT_FISHER_TULLY3
	const EVENT_BEAT_FISHER_WILTON2
	const EVENT_BEAT_FISHER_SCOTT
	const EVENT_BEAT_FISHER_WILTON3
; Twins
	const EVENT_BEAT_TWINS_AMY_AND_MAY
	const EVENT_BEAT_TWINS_ANN_AND_ANNE
	const EVENT_BEAT_TWINS_ANN_AND_ANNE2
	const EVENT_BEAT_TWINS_AMY_AND_MAY2
	const EVENT_BEAT_TWINS_JO_AND_ZOE
	const EVENT_BEAT_TWINS_JO_AND_ZOE2
	const EVENT_BEAT_TWINS_MEG_AND_PEG
	const EVENT_BEAT_TWINS_MEG_AND_PEG2
; Schoolboy
	const EVENT_BEAT_SCHOOLBOY_JACK
	const EVENT_BEAT_SCHOOLBOY_KIP
	const EVENT_BEAT_SCHOOLBOY_ALAN
	const EVENT_BEAT_SCHOOLBOY_JOHNNY
	const EVENT_BEAT_SCHOOLBOY_DANNY
	const EVENT_BEAT_SCHOOLBOY_TOMMY
	const EVENT_BEAT_SCHOOLBOY_DUDLEY
	const EVENT_BEAT_SCHOOLBOY_JOE
	const EVENT_BEAT_SCHOOLBOY_BILLY
	const EVENT_BEAT_SCHOOLBOY_CHAD
	const EVENT_BEAT_SCHOOLBOY_NATE
	const EVENT_BEAT_SCHOOLBOY_RICKY
	const EVENT_BEAT_SCHOOLBOY_JACK2
	const EVENT_BEAT_SCHOOLBOY_JACK3
	const EVENT_BEAT_SCHOOLBOY_ALAN2
	const EVENT_BEAT_SCHOOLBOY_ALAN3
	const EVENT_BEAT_SCHOOLBOY_CHAD2
	const EVENT_BEAT_SCHOOLBOY_CHAD3
; Picnicker
	const EVENT_BEAT_PICNICKER_LIZ
	const EVENT_BEAT_PICNICKER_GINA
	const EVENT_BEAT_PICNICKER_BROOKE
	const EVENT_BEAT_PICNICKER_KIM
	const EVENT_BEAT_PICNICKER_CINDY
	const EVENT_BEAT_PICNICKER_HOPE
	const EVENT_BEAT_PICNICKER_SHARON
	const EVENT_BEAT_PICNICKER_DEBRA
	const EVENT_BEAT_PICNICKER_GINA2
	const EVENT_BEAT_PICNICKER_ERIN
	const EVENT_BEAT_PICNICKER_LIZ2
	const EVENT_BEAT_PICNICKER_LIZ3
	const EVENT_BEAT_PICNICKER_HEIDI
	const EVENT_BEAT_PICNICKER_EDNA
	const EVENT_BEAT_PICNICKER_GINA3
	const EVENT_BEAT_PICNICKER_TIFFANY2
	const EVENT_BEAT_PICNICKER_TIFFANY3
	const EVENT_BEAT_PICNICKER_ERIN2
	const EVENT_BEAT_PICNICKER_TANYA
	const EVENT_BEAT_PICNICKER_TIFFANY
	const EVENT_BEAT_PICNICKER_ERIN3
; Guitarist
	const EVENT_BEAT_GUITARIST_CLYDE
	const EVENT_BEAT_GUITARIST_VINCENT
; Juggler
	const EVENT_BEAT_JUGGLER_IRWIN
	const EVENT_BEAT_JUGGLER_FRITZ
	const EVENT_BEAT_JUGGLER_HORTON
	const EVENT_BEAT_JUGGLER_IRWIN2
	const EVENT_BEAT_JUGGLER_IRWIN3
; Gentleman
	const EVENT_BEAT_GENTLEMAN_PRESTON
	const EVENT_BEAT_GENTLEMAN_EDWARD
	const EVENT_BEAT_GENTLEMAN_GREGORY
	const EVENT_BEAT_GENTLEMAN_VIRGIL
	const EVENT_BEAT_GENTLEMAN_ALFRED
; Scientist
	const EVENT_BEAT_SCIENTIST_ROSS
	const EVENT_BEAT_SCIENTIST_MITCH
	const EVENT_BEAT_SCIENTIST_JED
	const EVENT_BEAT_SCIENTIST_MARC
	const EVENT_BEAT_SCIENTIST_RICH
; Blackbelt
	const EVENT_BEAT_BLACKBELT_KENJI2
	const EVENT_BEAT_BLACKBELT_YOSHI
	const EVENT_BEAT_BLACKBELT_KENJI3
	const EVENT_BEAT_BLACKBELT_LAO
	const EVENT_BEAT_BLACKBELT_NOB
	const EVENT_BEAT_BLACKBELT_KIYO
	const EVENT_BEAT_BLACKBELT_LUNG
	const EVENT_BEAT_BLACKBELT_KENJI
	const EVENT_BEAT_BLACKBELT_WAI
; Beauty
	const EVENT_BEAT_BEAUTY_VICTORIA
	const EVENT_BEAT_BEAUTY_SAMANTHA
	const EVENT_BEAT_BEAUTY_JULIE
	const EVENT_BEAT_BEAUTY_JACLYN
	const EVENT_BEAT_BEAUTY_BRENDA
	const EVENT_BEAT_BEAUTY_CASSIE
	const EVENT_BEAT_BEAUTY_CAROLINE
	const EVENT_BEAT_BEAUTY_CARLENE
	const EVENT_BEAT_BEAUTY_JESSICA
	const EVENT_BEAT_BEAUTY_RACHAEL
	const EVENT_BEAT_BEAUTY_ANGELICA
	const EVENT_BEAT_BEAUTY_KENDRA
	const EVENT_BEAT_BEAUTY_VERONICA
	const EVENT_BEAT_COOLTRAINERF_JULIA
	const EVENT_BEAT_BEAUTY_THERESA
	const EVENT_BEAT_BEAUTY_VALERIE
; Nihon Gym Leaders
	const EVENT_BEAT_FALKNER
	const EVENT_BEAT_BUGSY
	const EVENT_BEAT_WHITNEY
	const EVENT_BEAT_MORTY
	const EVENT_BEAT_JASMINE
	const EVENT_BEAT_CHUCK
	const EVENT_BEAT_PRYCE
	const EVENT_BEAT_CLAIR
; SWIslands Gym Leaders
	const EVENT_BEAT_BROCK
	const EVENT_BEAT_MISTY
	const EVENT_BEAT_LTSURGE
	const EVENT_BEAT_ERIKA
	const EVENT_BEAT_JANINE
	const EVENT_BEAT_SABRINA
	const EVENT_BEAT_BLAINE
	const EVENT_BEAT_BLUE
; PokefanM
	const EVENT_BEAT_POKEFANM_WILLIAM
	const EVENT_BEAT_POKEFANM_DEREK
	const EVENT_BEAT_POKEFANM_ROBERT
	const EVENT_BEAT_POKEFANM_JOSHUA
	const EVENT_BEAT_POKEFANM_CARTER
	const EVENT_BEAT_POKEFANM_TREVOR
	const EVENT_BEAT_POKEFANM_BRANDON
	const EVENT_BEAT_POKEFANM_JEREMY
	const EVENT_BEAT_POKEFANM_COLIN
	const EVENT_BEAT_POKEFANM_DEREK2
	const EVENT_BEAT_POKEFANM_DEREK3
	const EVENT_BEAT_POKEFANM_ALEX
; PokefanF
	const EVENT_BEAT_POKEFANF_BEVERLY
	const EVENT_BEAT_POKEFANF_RUTH
	const EVENT_BEAT_POKEFANF_BEVERLY2
	const EVENT_BEAT_POKEFANF_BEVERLY3
	const EVENT_BEAT_POKEFANF_GEORGIA
; Unknown
	const EVENT_4DE
; Kimono Girl
	const EVENT_BEAT_KIMONO_GIRL_NAOKO
	const EVENT_BEAT_KIMONO_GIRL_SAYO
	const EVENT_BEAT_KIMONO_GIRL_ZUKI
	const EVENT_BEAT_KIMONO_GIRL_KUNI
	const EVENT_BEAT_KIMONO_GIRL_MIKI
; Pokemaniac
	const EVENT_BEAT_POKEMANIAC_LARRY
	const EVENT_BEAT_POKEMANIAC_ANDREW
	const EVENT_BEAT_POKEMANIAC_CALVIN
	const EVENT_BEAT_POKEMANIAC_SHANE
	const EVENT_BEAT_POKEMANIAC_BEN
	const EVENT_BEAT_POKEMANIAC_BRENT
	const EVENT_BEAT_POKEMANIAC_RON
	const EVENT_BEAT_POKEMANIAC_ETHAN
	const EVENT_BEAT_POKEMANIAC_BRENT2
	const EVENT_BEAT_POKEMANIAC_BRENT3
	const EVENT_BEAT_POKEMANIAC_ISSAC
	const EVENT_BEAT_POKEMANIAC_DONALD
	const EVENT_BEAT_POKEMANIAC_ZACH
; GruntM
	const EVENT_BEAT_ROCKET_GRUNTM_1
	const EVENT_BEAT_ROCKET_GRUNTM_2
	const EVENT_BEAT_ROCKET_GRUNTM_3
	const EVENT_BEAT_ROCKET_GRUNTM_4
	const EVENT_BEAT_ROCKET_GRUNTM_5
	const EVENT_BEAT_ROCKET_GRUNTM_6
	const EVENT_BEAT_ROCKET_GRUNTM_7
	const EVENT_BEAT_ROCKET_GRUNTM_8
	const EVENT_BEAT_ROCKET_GRUNTM_9
	const EVENT_BEAT_ROCKET_GRUNTM_10
	const EVENT_BEAT_ROCKET_GRUNTM_11
	const EVENT_BEAT_ROCKET_GRUNTM_12
	const EVENT_BEAT_ROCKET_GRUNTM_13
	const EVENT_BEAT_ROCKET_GRUNTM_14
	const EVENT_BEAT_ROCKET_GRUNTM_15
	const EVENT_BEAT_ROCKET_GRUNTM_16
	const EVENT_BEAT_ROCKET_GRUNTM_17
	const EVENT_BEAT_ROCKET_GRUNTM_18
	const EVENT_BEAT_ROCKET_GRUNTM_19
	const EVENT_BEAT_ROCKET_GRUNTM_20
	const EVENT_BEAT_ROCKET_GRUNTM_21
	const EVENT_BEAT_ROCKET_GRUNTM_22
	const EVENT_BEAT_ROCKET_GRUNTM_23
	const EVENT_BEAT_ROCKET_GRUNTM_24
	const EVENT_BEAT_ROCKET_GRUNTM_25
	const EVENT_BEAT_ROCKET_GRUNTM_26
	const EVENT_BEAT_ROCKET_GRUNTM_27
	const EVENT_BEAT_ROCKET_GRUNTM_28
	const EVENT_BEAT_ROCKET_GRUNTM_29
	const EVENT_BEAT_ROCKET_GRUNTM_30
	const EVENT_BEAT_ROCKET_GRUNTM_31
; GruntF
	const EVENT_BEAT_ROCKET_GRUNTF_1
	const EVENT_BEAT_ROCKET_GRUNTF_2
	const EVENT_BEAT_ROCKET_GRUNTF_3
	const EVENT_BEAT_ROCKET_GRUNTF_4
	const EVENT_BEAT_ROCKET_GRUNTF_5
; Lass
	const EVENT_BEAT_LASS_CARRIE
	const EVENT_BEAT_LASS_BRIDGET
	const EVENT_BEAT_LASS_ALICE
	const EVENT_BEAT_LASS_KRISE
	const EVENT_BEAT_LASS_CONNIE
	const EVENT_BEAT_LASS_LINDA
	const EVENT_BEAT_LASS_LAURA
	const EVENT_BEAT_LASS_SHANNON
	const EVENT_BEAT_LASS_MICHELLE
	const EVENT_BEAT_LASS_DANA
	const EVENT_BEAT_LASS_ELLEN
	const EVENT_BEAT_LASS_CONNIE2
	const EVENT_BEAT_LASS_CONNIE3
	const EVENT_BEAT_LASS_DANA2
	const EVENT_BEAT_LASS_DANA3
; Hiker
	const EVENT_BEAT_HIKER_ANTHONY2
	const EVENT_BEAT_HIKER_RUSSELL
	const EVENT_BEAT_HIKER_PHILLIP
	const EVENT_BEAT_HIKER_LEONARD
	const EVENT_BEAT_HIKER_ANTHONY
	const EVENT_BEAT_HIKER_BENJAMIN
	const EVENT_BEAT_HIKER_ERIK
	const EVENT_BEAT_HIKER_MICHAEL
	const EVENT_BEAT_HIKER_PARRY
	const EVENT_BEAT_HIKER_TIMOTHY
	const EVENT_BEAT_HIKER_BAILEY
	const EVENT_BEAT_HIKER_ANTHONY3
	const EVENT_BEAT_HIKER_TIM
	const EVENT_BEAT_HIKER_NOLAND
	const EVENT_BEAT_HIKER_SIDNEY
	const EVENT_BEAT_HIKER_KENNY
	const EVENT_BEAT_HIKER_JIM
	const EVENT_BEAT_HIKER_DANIEL
	const EVENT_BEAT_HIKER_PARRY2
	const EVENT_BEAT_HIKER_PARRY3
; Bug Catcher
	const EVENT_BEAT_BUG_CATCHER_DON
	const EVENT_BEAT_BUG_CATCHER_ROB
	const EVENT_BEAT_BUG_CATCHER_ED
	const EVENT_BEAT_BUG_CATCHER_WADE
	const EVENT_BEAT_BUG_CATCHER_BENNY
	const EVENT_BEAT_BUG_CATCHER_AL
	const EVENT_BEAT_BUG_CATCHER_JOSH
	const EVENT_BEAT_BUG_CATCHER_ARNIE
	const EVENT_BEAT_BUG_CATCHER_KEN
	const EVENT_BEAT_BUG_CATCHER_WADE2
	const EVENT_BEAT_BUG_CATCHER_WADE3
	const EVENT_BEAT_BUG_CATCHER_DOUG
	const EVENT_BEAT_BUG_CATCHER_ARNIE2
	const EVENT_BEAT_BUG_CATCHER_ARNIE3
; Officer
	const EVENT_BEAT_OFFICER_KEITH
	const EVENT_BEAT_OFFICER_DIRK
; CooltrainerM
	const EVENT_BEAT_COOLTRAINERM_NICK
	const EVENT_BEAT_COOLTRAINERM_AARON
	const EVENT_BEAT_COOLTRAINERM_PAUL
	const EVENT_BEAT_COOLTRAINERM_CODY
	const EVENT_BEAT_COOLTRAINERM_MIKE
	const EVENT_BEAT_COOLTRAINERM_GAVEN2
	const EVENT_BEAT_COOLTRAINERM_GAVEN3
	const EVENT_BEAT_COOLTRAINERM_RYAN
	const EVENT_BEAT_COOLTRAINERM_JAKE
	const EVENT_BEAT_COOLTRAINERM_GAVEN
	const EVENT_BEAT_COOLTRAINERM_BLAKE
	const EVENT_BEAT_COOLTRAINERM_BRIAN
	const EVENT_BEAT_COOLTRAINERM_ERICK
	const EVENT_BEAT_COOLTRAINERM_ANDY
	const EVENT_BEAT_COOLTRAINERM_TYLER
	const EVENT_BEAT_COOLTRAINERM_SEAN
	const EVENT_BEAT_COOLTRAINERM_KEVIN
	const EVENT_BEAT_COOLTRAINERM_STEVE
	const EVENT_BEAT_COOLTRAINERM_ALLEN; used in battle club
; CooltrainerF
	const EVENT_BEAT_COOLTRAINERF_GWEN
	const EVENT_BEAT_COOLTRAINERF_LOIS
	const EVENT_BEAT_COOLTRAINERF_FRAN
	const EVENT_BEAT_COOLTRAINERF_LOLA
	const EVENT_BEAT_COOLTRAINERF_KATE
	const EVENT_BEAT_COOLTRAINERF_IRENE
	const EVENT_BEAT_COOLTRAINERF_KELLY
	const EVENT_BEAT_COOLTRAINERF_JOYCE
	const EVENT_BEAT_COOLTRAINERF_BETH
	const EVENT_BEAT_COOLTRAINERF_REENA
	const EVENT_BEAT_COOLTRAINERF_MEGAN
	const EVENT_BEAT_COOLTRAINERF_BETH2
	const EVENT_BEAT_COOLTRAINERF_CAROL
	const EVENT_BEAT_COOLTRAINERF_QUINN
	const EVENT_BEAT_COOLTRAINERF_EMMA
	const EVENT_BEAT_COOLTRAINERF_CYBIL
	const EVENT_BEAT_COOLTRAINERF_JENN
	const EVENT_BEAT_COOLTRAINERF_BETH3
	const EVENT_BEAT_COOLTRAINERF_REENA2
	const EVENT_BEAT_COOLTRAINERF_REENA3
; ExecutiveF
	const EVENT_BEAT_ROCKET_EXECUTIVEF_1
	const EVENT_BEAT_ROCKET_EXECUTIVEF_2
; ExecutiveM
	const EVENT_BEAT_ROCKET_EXECUTIVEM_1
	const EVENT_BEAT_ROCKET_EXECUTIVEM_2
	const EVENT_BEAT_ROCKET_EXECUTIVEM_3
	const EVENT_BEAT_ROCKET_EXECUTIVEM_4
; Sailor
	const EVENT_BEAT_SAILOR_EUGENE
	const EVENT_BEAT_SAILOR_HUEY
	const EVENT_BEAT_SAILOR_TERRELL
	const EVENT_BEAT_SAILOR_KENT
	const EVENT_BEAT_SAILOR_ERNEST
	const EVENT_BEAT_SAILOR_JEFF
	const EVENT_BEAT_SAILOR_GARRETT
	const EVENT_BEAT_SAILOR_KENNETH
	const EVENT_BEAT_SAILOR_STANLY
	const EVENT_BEAT_SAILOR_HARRY
	const EVENT_BEAT_SAILOR_HUEY2
	const EVENT_BEAT_SAILOR_HUEY3
; Super Nerd
	const EVENT_BEAT_SUPER_NERD_STAN
	const EVENT_BEAT_SUPER_NERD_ERIC
	const EVENT_BEAT_SUPER_NERD_GREGG
	const EVENT_BEAT_SUPER_NERD_JAY
	const EVENT_BEAY_SUPER_NERD_DAVE
	const EVENT_BEAT_SUPER_NERD_SAM
	const EVENT_BEAT_SUPER_NERD_TOM
	const EVENT_BEAT_SUPER_NERD_PAT
	const EVENT_BEAT_SUPER_NERD_SHAWN
	const EVENT_BEAT_SUPER_NERD_TERU
; Medium
	const EVENT_BEAT_MEDIUM_MARTHA
	const EVENT_BEAT_MEDIUM_GRACE
	const EVENT_BEAT_MEDIUM_BETHANY
	const EVENT_BEAT_MEDIUM_MARGRET
	const EVENT_BEAT_MEDIUM_ETHEL
	const EVENT_BEAT_MEDIUM_REBECCA
	const EVENT_BEAT_MEDIUM_DORIS
; Skier
	const EVENT_BEAT_SKIER_ROXANNE
	const EVENT_BEAT_SKIER_CLARISSA
; SwimmerM
	const EVENT_BEAT_SWIMMERM_HAROLD
	const EVENT_BEAT_SWIMMERM_SIMON
	const EVENT_BEAT_SWIMMERM_RANDALL
	const EVENT_BEAT_SWIMMERM_CHARLIE
	const EVENT_BEAT_SWIMMERM_GEORGE
	const EVENT_BEAT_SWIMMERM_BERKE
	const EVENT_BEAT_SWIMMERM_KIRK
	const EVENT_BEAT_SWIMMERM_MATHEW
	const EVENT_BEAT_SWIMMERM_HAL
	const EVENT_BEAT_SWIMMERM_PATON
	const EVENT_BEAT_SWIMMERM_DARYL
	const EVENT_BEAT_SWIMMERM_WALTER
	const EVENT_BEAT_SWIMMERM_TONY
	const EVENT_BEAT_SWIMMERM_JEROME
	const EVENT_BEAT_SWIMMERM_TUCKER
	const EVENT_BEAT_SWIMMERM_RICK
	const EVENT_BEAT_SWIMMERM_CAMERON
	const EVENT_BEAT_SWIMMERM_SETH
	const EVENT_BEAT_SWIMMERM_JAMES
	const EVENT_BEAT_SWIMMERM_LEWIS
	const EVENT_BEAT_SWIMMERM_PARKER
; Youngster
	const EVENT_BEAT_YOUNGSTER_JOEY
	const EVENT_BEAT_YOUNGSTER_MIKEY
	const EVENT_BEAT_YOUNGSTER_ALBERT
	const EVENT_BEAT_YOUNGSTER_GORDON
	const EVENT_BEAT_YOUNGSTER_SAMUEL
	const EVENT_BEAT_YOUNGSTER_IAN
	const EVENT_BEAT_YOUNGSTER_JOEY2
	const EVENT_BEAT_YOUNGSTER_JOEY3
	const EVENT_BEAT_YOUNGSTER_WARREN
	const EVENT_BEAT_YOUNGSTER_JIMMY
	const EVENT_BEAT_YOUNGSTER_OWEN
	const EVENT_BEAT_YOUNGSTER_JASON
; Teacher
	const EVENT_BEAT_TEACHER_COLETTE
	const EVENT_BEAT_TEACHER_HILLARY
	const EVENT_BEAT_TEACHER_SHIRLEY
; Elite Four and Champion
	const EVENT_BEAT_ELITE_4_WILL
	const EVENT_BEAT_ELITE_4_KOGA
	const EVENT_BEAT_ELITE_4_BRUNO
	const EVENT_BEAT_ELITE_4_KAREN
	const EVENT_BEAT_CHAMPION_LANCE
; Crystal-exclusive trainer flags
	const EVENT_BEAT_COOLTRAINERM_DARIN
	const EVENT_BEAT_COOLTRAINERF_CARA
	const EVENT_BEAT_TWINS_LEA_AND_PIA
	const EVENT_BEAT_BUG_CATCHER_WAYNE
	const EVENT_BEAT_BEAUTY_OLIVIA
	const EVENT_BEAT_POKEFANF_JAIME
	const EVENT_BEAT_CAMPER_QUENTIN
	const EVENT_BEAT_POKEMANIAC_MILLER
	const EVENT_BEAT_SUPER_NERD_HUGH
	const EVENT_BEAT_SUPER_NERD_MARKUS
	const EVENT_BEAT_POKEFANM_REX
	const EVENT_BEAT_POKEFANM_ALLAN
	const EVENT_BEAT_SAGE_GAKU
	const EVENT_BEAT_SAGE_MASA
	const EVENT_BEAT_SAGE_KOJI
; ???
	const EVENT_ROUTE_106_ANTIDOTE
	const EVENT_JACK_READY_FOR_REMATCH
	const EVENT_BEVERLY_READY_FOR_REMATCH
	const EVENT_HUEY_READY_FOR_REMATCH
	const EVENT_GAVEN_READY_FOR_REMATCH
	const EVENT_BETH_READY_FOR_REMATCH
	const EVENT_JOSE_READY_FOR_REMATCH
	const EVENT_REENA_READY_FOR_REMATCH
	const EVENT_JOEY_READY_FOR_REMATCH
	const EVENT_WADE_READY_FOR_REMATCH
	const EVENT_RALPH_READY_FOR_REMATCH
	const EVENT_LIZ_READY_FOR_REMATCH
	const EVENT_ANTHONY_READY_FOR_REMATCH
	const EVENT_TODD_READY_FOR_REMATCH
	const EVENT_GINA_READY_FOR_REMATCH
	const EVENT_IRWIN_READY_FOR_REMATCH
	const EVENT_ARNIE_READY_FOR_REMATCH
	const EVENT_ALAN_READY_FOR_REMATCH
	const EVENT_DANA_READY_FOR_REMATCH
	const EVENT_CHAD_READY_FOR_REMATCH
	const EVENT_DEREK_READY_FOR_REMATCH
	const EVENT_CHRIS_READY_FOR_REMATCH
	const EVENT_BRENT_READY_FOR_REMATCH
	const EVENT_TIFFANY_READY_FOR_REMATCH
	const EVENT_VANCE_READY_FOR_REMATCH
	const EVENT_WILTON_READY_FOR_REMATCH
	const EVENT_KENJI_READY_FOR_REMATCH
	const EVENT_PARRY_READY_FOR_REMATCH
	const EVENT_ERIN_READY_FOR_REMATCH
	const EVENT_KIKAI_VILLAGE_MAX_ETHER
	const EVENT_JASMINE_RETURNED_TO_GYM
	const EVENT_SILVER_CAVE_ROOM_1_X_ACCURACY
	const EVENT_WHIRL_ISLAND_SW_GUARD_SPEC
	const EVENT_ICED_CAVERN_B1F_FULL_HEAL
	const EVENT_STAND_CITY_ZOO_MONS_10
	const EVENT_STAND_CITY_ZOO_MONS_9
	const EVENT_STAND_CITY_ZOO_MONS_8
	const EVENT_STAND_CITY_ZOO_MONS_7
	const EVENT_STAND_CITY_ZOO_MONS_6
	const EVENT_STAND_CITY_ZOO_MONS_5
	const EVENT_STAND_CITY_ZOO_MONS_4
	const EVENT_STAND_CITY_ZOO_MONS_3
	const EVENT_STAND_CITY_ZOO_MONS_2
	const EVENT_STAND_CITY_ZOO_MONS_1
	const EVENT_TEAM_ROCKET_BASE_B2F_DIRE_HIT
	const EVENT_TEAM_ROCKET_BASE_OFFICE_X_ACCURACY
	const EVENT_ALLOY_LIGHTHOUSE_5F_GREAT_BALL
	const EVENT_KURTS_HOUSE_SLOWPOKE
	const EVENT_VICTORY_ROAD_X_SPECIAL
	const EVENT_BURNED_TOWER_B1F_HP_UP
	const EVENT_BURNED_TOWER_B1F_HIDDEN_NUGGET
	const EVENT_BURNED_TOWER_B1F_HIDDEN_BURN_HEAL
	const EVENT_BURNED_TOWER_B1F_HIDDEN_ULTRA_BALL
	const EVENT_BURNED_TOWER_1F_BURN_HEAL
	const EVENT_BURNED_TOWER_1F_X_SPEED
	const EVENT_BURNED_TOWER_FIREBREATHER_DICK_ASHES
	const EVENT_BURNED_TOWER_FIREBREATHER_DICK_NORMAL
	const EVENT_FIVE_FLOOR_TOWER_4F_SUPER_POTION
	const EVENT_FIVE_FLOOR_TOWER_2F_X_DEFEND
	const EVENT_FIVE_FLOOR_TOWER_1F_PARLYZ_HEAL
	const EVENT_GOT_SECRETPOTION_FROM_PHARMACY
	const EVENT_TEKNOS_TIN_TOWER_ENTRANCE_SAGE_LEFT
	const EVENT_DECO_POSTER_4; kanto also why is this here
	const EVENT_GREAT_EAST_STRAIT_DIRE_HIT
	const EVENT_TATSUGO_PATH_X_SPECIAL
	const EVENT_ROUTE_102_BIPETAL
	const EVENT_CHRIS_ASKED_FOR_PHONE_NUMBER
	const EVENT_BEAT_FISHER_CHRIS
	const EVENT_TEKNOS_TIN_TOWER_ENTRANCE_SAGE_RIGHT
	const EVENT_SILVER_IN_WESTPORT
	const EVENT_BEAT_FLEDGLING_HUGO
	const EVENT_ROUTE_115_ROCKS_DEMOLISHED
	const EVENT_ROCKET_MACHINE_DAMAGED
	const EVENT_ROUTE_101N_TREE_CUT
	const EVENT_ROUTE_102_TREE_CUT
	const EVENT_SUNPOINT_SMASH_ROCKS
	const EVENT_PAGOTA_TREE_CUT
	const EVENT_SILVER_AT_ROUTE_101_GATE
	const EVENT_62E
	const EVENT_62F
	const EVENT_630
	const EVENT_631
	const EVENT_632
	const EVENT_633
	const EVENT_634
	const EVENT_635
	const EVENT_636
	const EVENT_637
	const EVENT_638
	const EVENT_639
	const EVENT_63A
	const EVENT_63B
	const EVENT_63C
	const EVENT_63D
	const EVENT_63E
	const EVENT_63F
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `const` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
; Nihon itemballs
	const EVENT_FLAMBEAR_POKEBALL_IN_OAK_LAB_BACK_ROOM
	const EVENT_CRUISEAL_POKEBALL_IN_OAK_LAB_BACK_ROOM
	const EVENT_HAPPA_POKEBALL_IN_OAK_LAB_BACK_ROOM
	const EVENT_PAGOTA_CITY_PP_UP
	const EVENT_PAGOTA_CITY_RARE_CANDY
	const EVENT_KIKAI_VILLAGE_ELIXER
	const EVENT_KIKAI_VILLAGE_TM_DETECT
	const EVENT_SPROUT_TOWER1F_PARLYZ_HEAL
	const EVENT_SPROUT_TOWER2F_X_ACCURACY
	const EVENT_FIVE_FLOOR_TOWER_3F_POTION
	const EVENT_FIVE_FLOOR_TOWER_3F_ESCAPE_ROPE
	const EVENT_RAINBOW_ISLAND_FULL_HEAL
	const EVENT_FIVE_FLOOR_TOWER_4F_ULTRA_BALL
	const EVENT_FIVE_FLOOR_TOWER_4F_PP_UP
	const EVENT_FIVE_FLOOR_TOWER_4F_ESCAPE_ROPE
	const EVENT_FIVE_FLOOR_TOWER_5F_RARE_CANDY
	const EVENT_FORKED_STRAIT_WEST_MAX_REVIVE
	const EVENT_FORKED_STRAIT_EAST_NUGGET
	const EVENT_FORKED_STRAIT_EAST_MAX_ELIXER
	const EVENT_FORKED_STRAIT_EAST_FULL_RESTORE
	const EVENT_TEAM_ROCKET_BASE_B2F_ULTRA_BALL
	const EVENT_WESTPORT_UNDERGROUND_WAREHOUSE_ULTRA_BALL
	const EVENT_BURNED_TOWER_1F_HP_UP
	const EVENT_BURNED_TOWER_B1F_TM_ENDURE
	const EVENT_NATIONAL_PARK_PARLYZ_HEAL
	const EVENT_NATIONAL_PARK_TM_DIG
	const EVENT_BOULDER_MINE_1F_GREAT_BALL
	const EVENT_BOULDER_MINE_1F_X_ATTACK
	const EVENT_BOULDER_MINE_1F_POTION
	const EVENT_BOULDER_MINE_1F_AWAKENING
	const EVENT_BOULDER_MINE_B1F_TM_SWIFT
	const EVENT_BOULDER_MINE_B1F_X_DEFEND
	const EVENT_BOULDER_MINE_B5F_ELIXER
	const EVENT_BOULDER_MINE_B5F_HYPER_POTION
	const EVENT_SLOWPOKE_WELL_B1F_SUPER_POTION
	const EVENT_SLOWPOKE_WELL_B2F_TM_RAIN_DANCE
	const EVENT_ENDON_CAVE_2F_ETHER
	const EVENT_ALLOY_LIGHTHOUSE_5F_RARE_CANDY
	const EVENT_VICTORY_ROAD_2F_HELIX_FOSSIL
	const EVENT_ALLOY_LIGHTHOUSE_5F_TM_SWAGGER
	const EVENT_GOT_TEAM_ROCKET_AMULET_COIN
	const EVENT_TEAM_ROCKET_BASE_OFFICE_HYPER_POTION
	const EVENT_TEAM_ROCKET_BASE_OFFICE_NUGGET
	const EVENT_TEAM_ROCKET_BASE_OFFICE_GUARD_SPEC
	const EVENT_TEAM_ROCKET_BASE_B1F_TM_THIEF
	const EVENT_TEAM_ROCKET_BASE_B2F_PROTEIN
	const EVENT_TEAM_ROCKET_BASE_B2F_X_SPECIAL
	const EVENT_TEAM_ROCKET_BASE_B2F_ENERGY_WALL
	const EVENT_TEAM_ROCKET_BASE_B2F_ICE_HEAL
	const EVENT_JADE_FOREST_REVIVE
	const EVENT_GOT_COIN_CASE_FROM_GAMBLER
	const EVENT_WESTPORT_UNDERGROUND_SWITCH_ROOM_ENTRANCES_SMOKE_BALL
	const EVENT_WESTPORT_UNDERGROUND_SWITCH_ROOM_ENTRANCES_FULL_HEAL
	const EVENT_WESTPORT_DEPT_STORE_B1F_ETHER
	const EVENT_WESTPORT_DEPT_STORE_B1F_AMULET_COIN
	const EVENT_WESTPORT_DEPT_STORE_B1F_BURN_HEAL
	const EVENT_WESTPORT_DEPT_STORE_B1F_ULTRA_BALL
	const EVENT_WESTPORT_UNDERGROUND_WAREHOUSE_MAX_ETHER
	const EVENT_WESTPORT_UNDERGROUND_WAREHOUSE_TM_SLEEP_TALK
	const EVENT_CHARRED_SUMMIT_CAVE_ETHER
	const EVENT_CHARRED_SUMMIT_CAVE_REVIVE
	const EVENT_JOULE_CAVE_1F_ESCAPE_ROPE
	const EVENT_JOULE_CAVE_1F_MAX_REVIVE
	const EVENT_JOULE_CAVE_1F_HYPER_POTION
	const EVENT_ICED_CAVERN_1F_MAX_POTION
	const EVENT_ICED_CAVERN_1F_RARE_CANDY
	const EVENT_ICED_CAVERN_1F_TM_DEFENSE_CURL
	const EVENT_ICED_CAVERN_1F_DRAGON_SCALE
	const EVENT_ICED_CAVERN_1F_ELIXER
	const EVENT_ICED_CAVERN_1F_ESCAPE_ROPE
	const EVENT_ICED_CAVERN_B1F_HYPER_POTION
	const EVENT_ICED_CAVERN_B1F_CARBOS
	const EVENT_GOT_HM07_WATERFALL
	const EVENT_DEEPWATER_PASSAGE_B2F_PP_UP
	const EVENT_MAGMA_SHAFT_B1F_IRON
	const EVENT_MAGMA_SHAFT_B2F_FULL_HEAL
	const EVENT_MAGMA_SHAFT_B2F_MAX_POTION
	const EVENT_MAGMA_SHAFT_1F_TM_REST
	const EVENT_DEEPWATER_PASSAGE_B1F_NEVERMELTICE
	const EVENT_WHIRL_ISLAND_1F_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_SW_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B1F_CARBOS
	const EVENT_WHIRL_ISLAND_B1F_DETECT_ORB
	const EVENT_WHIRL_ISLAND_B1F_NUGGET
	const EVENT_WHIRL_ISLAND_B1F_ESCAPE_ROPE
	const EVENT_WHIRL_ISLAND_B2F_POISON_STONE
	const EVENT_WHIRL_ISLAND_B2F_MAX_REVIVE
	const EVENT_WHIRL_ISLAND_B2F_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_PROTEIN
	const EVENT_SILVER_CAVE_ROOM_1_ESCAPE_ROPE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_MAX_REVIVE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_FULL_RESTORE
	const EVENT_AMPARE_CAVERN_B1F_POTION
	const EVENT_AMPARE_CAVERN_B1F_FULL_HEAL
	const EVENT_AMPARE_CAVERN_B1F_HYPER_POTION
	const EVENT_AMPARE_CAVERN_1F_REVIVE
	const EVENT_AMPARE_CAVERN_1F_TM_SNORE
	const EVENT_VICTORY_ROAD_TM_EARTHQUAKE
	const EVENT_VICTORY_ROAD_MAX_REVIVE
	const EVENT_VICTORY_ROAD_FULL_RESTORE
	const EVENT_VICTORY_ROAD_FULL_HEAL
	const EVENT_VICTORY_ROAD_HP_UP
	const EVENT_DRAGONS_DEN_B1F_DRAGON_FANG
	const EVENT_TOHJO_FALLS_MOON_STONE
	const EVENT_ROUTE_U6U_MAX_ELIXER; zap cannon in darkcavepagotaentrance
	const EVENT_ROUTE_115_TM_SOLARBEAM
	const EVENT_ROUTE_115_RARE_CANDY
	const EVENT_ROUTE_101_POTION
	const EVENT_ROUTE_101_POTION_2
	const EVENT_ROUTE_106_POTION
	const EVENT_ROUTE_106_POKE_BALL
	const EVENT_ROUTE_112_GREAT_BALL
	const EVENT_ROUTE_112_REPEL
	const EVENT_ROUTE_103_TM_ROLLOUT
	const EVENT_ROUTE_U4U_ULTRA_BALL
	const EVENT_ROUTE_U4U_SUPER_POTION
	const EVENT_BOARDWALK_MAX_ETHER
	const EVENT_KIKAI_STRAIT_MAX_REVIVE
	const EVENT_KIKAI_STRAIT_ULTRA_BALL
	const EVENT_VICTORY_ROAD_2F_NUGGET
	const EVENT_TATSUGO_PATH_REVIVE
	const EVENT_TATSUGO_PATH_ELIXER
	const EVENT_VICTORY_ROAD_2F_TOXIC
	const EVENT_GREAT_EAST_STRAIT_X_SPEED; route 7 tm roar
; Nihon people
	const EVENT_RIVAL_SILENT_TOWN
	const EVENT_RIVAL_OAK_LAB_FRONT_ROOM
	const EVENT_BLUE_OAK_LAB_FRONT_ROOM
	const EVENT_DAISY_OAK_LAB_FRONT_ROOM
	const EVENT_BLUE_SILENT_TOWN
	const EVENT_SILVER_IN_OAK_LAB_BACK_ROOM
	const EVENT_BLUE_IN_OAK_LAB_BACK_ROOM
	const EVENT_PAGOTA_GYM_FALKNER
	const EVENT_KURTS_HOUSE_FALKNER
	const EVENT_RIVAL_CROWN_CITY
	const EVENT_ENTEI_APPEARS; entei event
	const EVENT_RIVAL_TEAM_ROCKET_BASE; suicune event
	const EVENT_RIVAL_WESTPORT_UNDERGROUND
	const EVENT_RIVAL_VICTORY_ROAD
	const EVENT_RIVAL_ALLOY_CITY
	const EVENT_RIVAL_SPROUT_TOWER
	const EVENT_103_SLOWPOKE_SALESMAN ;used for the people in slowpoke well b2f, and rockets in guardhouse, and tail salesman
	const EVENT_RIVAL_DRAGONS_DEN
	const EVENT_PLAYERS_HOUSE_MOM_1
	const EVENT_PLAYERS_HOUSE_MOM_2
	const EVENT_MR_POKEMONS_HOUSE_OAK
	const EVENT_PAGOTA_CITY_EARL; used for noting that the ho-oh story man isn't home, disappears sages in tower as well
	const EVENT_EARLS_ACADEMY_EARL; used for noting that you have triggered the ho-oh event
	const EVENT_WESTPORT_CITY_ROCKET_SCOUT; used for setting the rocket base console to off
	const EVENT_WESTPORT_CITY_ROCKET_TAKEOVER
	const EVENT_RADIO_TOWER_ROCKET_TAKEOVER
	const EVENT_WESTPORT_CITY_CIVILIANS
	const EVENT_RADIO_TOWER_CIVILIANS_AFTER
	const EVENT_RADIO_TOWER_BLACKBELT_BLOCKS_STAIRS
	const EVENT_ALLOY_LIGHTHOUSE_JASMINE
	const EVENT_ALLOY_GYM_JASMINE
	const EVENT_KIKAI_VILLAGE_LANCE
	const EVENT_OLD_MAHOGANY_MART_LANCE_AND_DRAGONITE
	const EVENT_TEAM_ROCKET_BASE_B1F_LANCE
	const EVENT_TEAM_ROCKET_BASE_B2F_LANCE_PASSWORDS
	const EVENT_DRAGONS_DEN_CLAIR
	const EVENT_TEAM_ROCKET_BASE_SECURITY_GRUNTS
	const EVENT_TEAM_ROCKET_BASE_POPULATION
	const EVENT_TEAM_ROCKET_BASE_B2F_EXECUTIVE
	const EVENT_BOARDWALK_GATE_ROCKETS; used for making hidden stairs appear
	const EVENT_TEAM_ROCKET_BASE_B1F_EXECUTIVE
	const EVENT_TEAM_ROCKET_BASE_B1F_GRUNT_WITH_EXECUTIVE
	const EVENT_TEAM_ROCKET_BASE_B1F_DRAGONITE
	const EVENT_TEAM_ROCKET_BASE_B1F_ELECTRODE_1; used to make imposter and executive disappear in boss room
	const EVENT_TEAM_ROCKET_BASE_B1F_ELECTRODE_2
	const EVENT_TEAM_ROCKET_BASE_B1F_ELECTRODE_3
	const EVENT_BLUE_FOREST_SUPER_NERD_BLOCKS_GYM; used for workers on route 32/112
	const EVENT_BLUE_FOREST_SUPER_NERD_DOES_NOT_BLOCK_GYM; this is the event for clearing the rocket hideout in stand city, but not the the radio tower
	const EVENT_DAY_CARE_MAN_IN_DAY_CARE
	const EVENT_DAY_CARE_MAN_ON_ROUTE_113
	const EVENT_DAY_CARE_MON_1
	const EVENT_DAY_CARE_MON_2
	const EVENT_STAND_CITY_ZOO_MONS; used, this is what makes zoo pokes disappear in stand city
	const EVENT_ROUTE_113_ROUTE_114_GATE_TEACHER_BEHIND_COUNTER
	const EVENT_ROUTE_113_ROUTE_114_GATE_LASS
	const EVENT_ROUTE_113_ROUTE_114_GATE_TEACHER_IN_WALKWAY
	const EVENT_JADE_FOREST_LASS; used for making silver and imposter disappear after initial encounter by computer console
	const EVENT_COPYCAT_1
	const EVENT_COPYCAT_2
	const EVENT_WESTPORT_SALE_OFF
	const EVENT_WESTPORT_SALE_ON
	const EVENT_6F2
	const EVENT_JADE_FOREST_APPRENTICE; used, this marks that imposter oak has given his speech
	const EVENT_JADE_FOREST_CHARCOAL_MASTER
	const EVENT_BIRDON_MILK_BAR_FARFETCH_D ;used for boulder in alloy gym
	const EVENT_BIRDON_MILK_BAR_APPRENTICE ;used for boulder in alloy gym
	const EVENT_BIRDON_MILK_BAR_BOSS ;used for boulder in alloy gym
	const EVENT_ROUTE_102_SILVER
	const EVENT_RAIKOU_APPEARS; raikou event
	const EVENT_BIRDON_TOWN_SLOWPOKETAIL_ROCKET
	const EVENT_SLOWPOKE_WELL_SLOWPOKES; used to make kurt and captain disappear before ho oh event
	const EVENT_SLOWPOKE_WELL_ROCKETS
	const EVENT_GUIDE_GENT_IN_HIS_HOUSE
	const EVENT_GUIDE_GENT_VISIBLE_IN_CROWN
	const EVENT_OAK2S_AIDE_IN_PAGOTA_POKEMON_CENTER
	const EVENT_OAK2S_AIDE_IN_LAB
	const EVENT_COP_IN_OAK_LAB_BACK_ROOM
	const EVENT_RUINS_OF_ALPH_OUTSIDE_SCIENTIST
	const EVENT_RUINS_OF_ALPH_RESEARCH_CENTER_SCIENTIST
	const EVENT_RUINS_OF_ALPH_INNER_CHAMBER_TOURISTS
	const EVENT_BOULDER_IN_BLUE_FOREST_GYM_1
	const EVENT_BOULDER_IN_BLUE_FOREST_GYM_2
	const EVENT_BOULDER_IN_BLUE_FOREST_GYM_3
	const EVENT_BOULDER_IN_ICE_PATH_1
	const EVENT_BOULDER_IN_ICE_PATH_2
	const EVENT_BOULDER_IN_ICE_PATH_3
	const EVENT_BOULDER_IN_ICE_PATH_4
	const EVENT_BOULDER_IN_ICE_PATH_1A
	const EVENT_BOULDER_IN_ICE_PATH_2A
	const EVENT_BOULDER_IN_ICE_PATH_3A
	const EVENT_BOULDER_IN_ICE_PATH_4A
	const EVENT_MYSTERY_GIFT_DELIVERY_GUY
	const EVENT_MET_BILL
	const EVENT_TEKNOS_POKE_CENTER_BILL
	const EVENT_ROUTE_105_BATTLE; used, this is the password to shut the console down
	const EVENT_ROUTE_105_YOUNGSTER_JOEY
	const EVENT_BUG_CATCHING_CONTESTANT_1A
	const EVENT_BUG_CATCHING_CONTESTANT_2A
	const EVENT_BUG_CATCHING_CONTESTANT_3A
	const EVENT_BUG_CATCHING_CONTESTANT_4A
	const EVENT_BUG_CATCHING_CONTESTANT_5A
	const EVENT_BUG_CATCHING_CONTESTANT_6A
	const EVENT_BUG_CATCHING_CONTESTANT_7A
	const EVENT_BUG_CATCHING_CONTESTANT_8A
	const EVENT_BUG_CATCHING_CONTESTANT_9A
	const EVENT_BUG_CATCHING_CONTESTANT_10A
	const EVENT_BUG_CATCHING_CONTESTANT_1B
	const EVENT_BUG_CATCHING_CONTESTANT_2B
	const EVENT_BUG_CATCHING_CONTESTANT_3B
	const EVENT_BUG_CATCHING_CONTESTANT_4B
	const EVENT_BUG_CATCHING_CONTESTANT_5B
	const EVENT_BUG_CATCHING_CONTESTANT_6B
	const EVENT_BUG_CATCHING_CONTESTANT_7B
	const EVENT_BUG_CATCHING_CONTESTANT_8B
	const EVENT_BUG_CATCHING_CONTESTANT_9B
	const EVENT_BUG_CATCHING_CONTESTANT_10B
	const EVENT_WESTPORT_PORT_SAILOR_AT_GANGWAY
	const EVENT_AMAMI_PORT_SAILOR_AT_GANGWAY
	const EVENT_FAST_SHIP_1F_GENTLEMAN
	const EVENT_FAST_SHIP_CABINS_NNW_NNE_NE_SAILOR
	const EVENT_FAST_SHIP_B1F_SAILOR_LEFT
	const EVENT_FAST_SHIP_B1F_SAILOR_RIGHT
	const EVENT_RETURNED_FUEL_LINE; used for returning ship part to dock sailor, also marking that islands are fully open
	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_1; unused, needs to be reset if going to use
	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_2; used for setting up scene with captain and broken ship
	const EVENT_WESTPORT_PORT_PASSAGE_POKEFAN_M
	const EVENT_ROUTE_103_NATIONAL_PARK_GATE_YOUNGSTER
	const EVENT_KIKAI_VILLAGE_CIVILIANS
	const EVENT_OLD_MAHOGANY_MART_OWNERS
	const EVENT_WESTPORT_PORT_SPRITES_BEFORE_HALL_OF_FAME
	const EVENT_WESTPORT_PORT_SPRITES_AFTER_HALL_OF_FAME
	const EVENT_FAST_SHIP_PASSENGERS_FIRST_TRIP
	const EVENT_FAST_SHIP_PASSENGERS_EASTBOUND
	const EVENT_FAST_SHIP_PASSENGERS_WESTBOUND
	const EVENT_FIVE_FLOOR_TOWER_ROOF_HO_OH
	const EVENT_WHIRL_ISLAND_BLISSEY_CHAMBER_BLISSEY
	const EVENT_KURTS_HOUSE_KURT_1
	const EVENT_KURTS_HOUSE_KURT_2
	const EVENT_SLOWPOKE_WELL_KURT ; 740
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
	const EVENT_PLAYERS_HOUSE_2F_DOLL_2
	const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
	const EVENT_ROUTE_103_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_103_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_STAND_CITY_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_STAND_CITY_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_WESTPORT_TRAIN_STATION_GENTLEMAN
	const EVENT_BURNED_TOWER_B1F_BEASTS_1
	const EVENT_BURNED_TOWER_B1F_BEASTS_2
	const EVENT_BLUE_FOREST_GRAMPS_BLOCKS_DRAGONS_DEN; used, clair blocks cave of dragons
	const EVENT_BLUE_FOREST_GRAMPS_NOT_BLOCKING_DRAGONS_DEN; used, for clair in her house
	const EVENT_RUINS_OF_ALPH_KABUTO_CHAMBER_RECEPTIONIST
	const EVENT_OPENED_MT_SILVER
	const EVENT_FOUGHT_SNORLAX ; 750
	const EVENT_KIKAI_VILLAGE_RED_GYARADOS
	const EVENT_WESTPORT_UNDERGROUND_GRANNY
	const EVENT_WESTPORT_UNDERGROUND_GRAMPS
	const EVENT_WESTPORT_UNDERGROUND_OLDER_HAIRCUT_BROTHER
	const EVENT_WESTPORT_UNDERGROUND_YOUNGER_HAIRCUT_BROTHER
	const EVENT_SANSKRIT_TOWN_POKEFAN_M_BLOCKS_EAST
	const EVENT_ROCKETS_TAKE_OVER_AQUARIUM ; this is used for the rockets in the aquarium
	const EVENT_ROUTE_112_FRIEDA_OF_FRIDAY
	const EVENT_ROUTE_101_TUSCANY_OF_TUESDAY
	const EVENT_ROUTE_102_ARTHUR_OF_THURSDAY
	const EVENT_SILENT_HILLS_SUNNY_OF_SUNDAY
	const EVENT_KIKAI_VILLAGE_WESLEY_OF_WEDNESDAY
	const EVENT_BLUE_FOREST_SANTOS_OF_SATURDAY
	const EVENT_ROUTE_110_MONICA_OF_MONDAY
	const EVENT_LANCES_ROOM_OAK_AND_MARY
	const EVENT_BOULDER_MINE_B5F_LAPRAS ; 760
	const EVENT_TEAM_ROCKET_DISBANDED
	const EVENT_RED_IN_MT_SILVER
	const EVENT_WESTPORT_DEPT_STORE_5F_HAPPINESS_EVENT_LADY
	const EVENT_BOULDER_MINE_WHITNEY ; morty in the mines, actually whitney cause im dumb
	const EVENT_WHITNEY_BACK_IN_TEKNOS_GYM ;morty in the gym, actually whitney
	const EVENT_RANG_HELIX_FOSSIL_1
	const EVENT_RANG_HELIX_FOSSIL_2
	const EVENT_FLORIA_AT_FLOWER_SHOP ;used for making npcs appear and disappear at the south point docks
	const EVENT_FLORIA_AT_BIPETAL
	const EVENT_WESTPORT_CITY_MOVE_TUTOR
	const EVENT_BOARDWALK_GAME_CORNER_MOVE_TUTOR
; SWIslands people
	const EVENT_KUME_POINT_ROCKET
	const EVENT_JADE_FOREST_SNORLAX_ROOM_ROCKET
	const EVENT_MERIDIAN_PATH_MISTY_BOYFRIEND
	const EVENT_TRAINERS_IN_JADE_FOREST_SNORLAX_ROOM
	const EVENT_JADE_FOREST_SNORLAX ; 770
	const EVENT_ROCKETS_IN_BOAT_AT_SUNPOINT ;rockets and boat in route 5/south point docks, and honto town base
	const EVENT_RYUKYU_TRAIN_STATION_POPULATION
	const EVENT_COPYCATS_HOUSE_2F_DOLL
	const EVENT_AMAMI_FAN_CLUB_DOLL
	const EVENT_BLUE_IN_FROSTPOINT
	const EVENT_TEAM_ROCKET_SHIP_BASE_BLUE
	const EVENT_SEAFOAM_GYM_GYM_GUY
	const EVENT_MT_MOON_SQUARE_ROCK
	const EVENT_MT_MOON_SQUARE_CLEFAIRY
	const EVENT_MT_MOON_RIVAL
	const EVENT_MOUNT_FUJI_POKECENTER_RIVAL
	const EVENT_TELEPORT_GUY; also used to make other characters on island appear
; SWIslands itemballs
	const EVENT_PICKED_UP_FOCUS_BAND
	const EVENT_BOULDER_MINE_B2F_ELIXER
	const EVENT_BOULDER_MINE_B2F_TM_STEEL_WING
	const EVENT_BOULDER_MINE_B3F_IRON ; 780
	const EVENT_BOULDER_MINE_B3F_PP_UP
	const EVENT_BOULDER_MINE_B3F_REVIVE
	const EVENT_ROUTE_116_DIRE_HIT
	const EVENT_ROUTE_116_MAX_POTION
	const EVENT_ROUTE_116_CARBOS
	const EVENT_ROUTE_116_ELIXER
	const EVENT_ROUTE_118_HP_UP
	const EVENT_URASOE_TRAIL_CALCIUM
	const EVENT_URASOE_TRAIL_NUGGET
	const EVENT_ROUTE_U11U_PP_UP
	const EVENT_MERIDIAN_PATH_PROTEIN
; New to Crystal
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_1
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_2
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_FISHER
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_YOUNGSTERS
	const EVENT_KANTO_RESTAURANT_CLAIR ; 790
	const EVENT_BATTLE_TOWER_BATTLE_ROOM_YOUNGSTER
	const EVENT_PLAYERS_HOUSE_1F_NEIGHBOR
	const EVENT_PLAYERS_NEIGHBORS_HOUSE_NEIGHBOR
	const EVENT_PICKED_UP_GOLD_BERRY_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_MYSTERYBERRY_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_REVIVAL_HERB_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_CHARCOAL_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_BERRY_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_PSNCUREBERRY_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_HEAL_POWDER_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_ENERGYPOWDER_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_MYSTERYBERRY_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_MYSTIC_WATER_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_STARDUST_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_STAR_PIECE_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_GOLD_BERRY_FROM_AERODACTYL_ITEM_ROOM ; 7a0
	const EVENT_PICKED_UP_MOON_STONE_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_PICKED_UP_HEAL_POWDER_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_PICKED_UP_ENERGY_ROOT_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_BIRDON_TOWN_KURT
	const EVENT_JADE_FOREST_KURT
	const EVENT_JOULE_CAVE_1F_MAX_POTION
	const EVENT_JOULE_CAVE_1F_NUGGET
	const EVENT_BIRDON_GYM_GRAMPS; used for grandpa at home
	const EVENT_TEKNOS_CITY_GRAMPS; used for grandpa at mine
	const EVENT_EUSINE_IN_BURNED_TOWER
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_1; used for granddaughter in mine
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_2; used for granddaughter at home
	const EVENT_SUNPOINT_CITY_EUSINE
	const EVENT_SAW_SUICUNE_AT_SUNPOINT_CITY
	const EVENT_SAW_SUICUNE_ON_ROUTE_U4U
	const EVENT_SAW_SUICUNE_ON_ROUTE_102 ; 7b0
	const EVENT_TEKNOS_TIN_TOWER_ENTRANCE_WANDERING_SAGE
	const EVENT_HYDRAULIC_CAVE_SUICUNE
	const EVENT_HYDRAULIC_CAVE_ENTEI; used for getting starter from scientist
	const EVENT_HYDRAULIC_CAVE_RAIKOU
	const EVENT_HYDRAULIC_CAVE_EUSINE
	const EVENT_HYDRAULIC_CAVE_WISE_TRIO_1
	const EVENT_SET_WHEN_FOUGHT_HO_OH
	const EVENT_ROUTE_105_ANTIDOTE
	const EVENT_JADE_FOREST_X_ATTACK
	const EVENT_JADE_FOREST_ANTIDOTE
	const EVENT_JADE_FOREST_ETHER
	const EVENT_ROUTE_113_NUGGET
	const EVENT_KIKAI_STRAIT_MAX_REPEL
	const EVENT_DEEPWATER_PASSAGE_B2F_PROTEIN
	const EVENT_DRAGONS_DEN_B1F_CALCIUM
	const EVENT_DRAGONS_DEN_B1F_MAX_ELIXER ; 7c0
	const EVENT_SILVER_CAVE_ROOM_1_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_CALCIUM
	const EVENT_SILVER_CAVE_ROOM_2_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_PP_UP
	const EVENT_HYDRAULIC_CAVE_WISE_TRIO_2
	const EVENT_FORKED_STRAIT_NORTH_MAX_POTION
	const EVENT_TIN_TOWER_9F_HP_UP
	const EVENT_JOULE_CAVE_1F_IRON
	const EVENT_JOULE_CAVE_1F_ULTRA_BALL
	const EVENT_ICED_CAVERN_B1F_FULL_RESTORE
	const EVENT_ICED_CAVERN_B1F_MAX_ETHER
	const EVENT_ICED_CAVERN_B1F_PP_UP
	const EVENT_RADIO_TOWER_5F_ULTRA_BALL
	const EVENT_AMPARE_CAVERN_B1F_DIRE_HIT
	const EVENT_BATTLE_TOWER_OUTSIDE_SAILOR
	const EVENT_BEAT_ENGINEER_DAVIDSON
	const EVENT_BEAT_ENGINEER_LANDON
	const EVENT_BEAT_ENGINEER_RICARDO
	const EVENT_BEAT_ENGINEER_MARKSON
	const EVENT_BEAT_SPORTSMAN_JACOB
	const EVENT_BEAT_SPORTSMAN_MANNY
	const EVENT_BEAT_SPORTSMAN_ARTHUR
	const EVENT_BEAT_SPORTSMAN_BRYSON
	const EVENT_BEAT_SOLDIER_GERALD
	const EVENT_BEAT_SOLDIER_ANTONIO
	const EVENT_BEAT_SOLDIER_DAN
	const EVENT_BEAT_SOLDIER_WARNELL
	const EVENT_BEAT_INSTRUCTOR_CLIFF
	const EVENT_BEAT_INSTRUCTOR_RAND
	const EVENT_BEAT_INSTRUCTOR_MORGAN
	const EVENT_BEAT_INSTRUCTOR_GEOFF
	const EVENT_BEAT_FLEDGLING_CLAYTON
	const EVENT_BEAT_FLEDGLING_EARNEST
	const EVENT_BEAT_FLEDGLING_HIDALGO
	const EVENT_BEAT_FLEDGLING_PAULSON
NUM_EVENTS EQU const_value ; 7d0
