; GetSGBLayout arguments (see engine/gfx/cgb_layouts.asm and engine/gfx/sgb_layouts.asm)
	const_def
	const SCGB_BATTLE_GRAYSCALE
	const SCGB_BATTLE_COLORS
	const SCGB_POKEGEAR_PALS
	const SCGB_STATS_SCREEN_HP_PALS
	const SCGB_POKEDEX
	const SCGB_SLOT_MACHINE
	const SCGB_BETA_TITLE_SCREEN
	const SCGB_GS_INTRO
	const SCGB_DIPLOMA
	const SCGB_MAPPALS
	const SCGB_PARTY_MENU
	const SCGB_EVOLUTION
	const SCGB_PACKPALS_YELLOWRED
	const SCGB_NAMING_SCREEN
	const SCGB_MOVE_LIST
	const SCGB_BETA_PIKACHU_MINIGAME
	const SCGB_POKEDEX_SEARCH_OPTION
	const SCGB_BETA_POKER
	const SCGB_POKEPIC
	const SCGB_BETA_POKEGEAR_PALS
	const SCGB_PACKPALS_BLUEGREEN
	const SCGB_TRAINER_CARD
	const SCGB_POKEDEX_UNOWN_MODE
	const SCGB_BILLS_PC
	const SCGB_UNOWN_PUZZLE
	const SCGB_GAMEFREAK_LOGO
	const SCGB_PLAYER_OR_MON_FRONTPIC_PALS
	const SCGB_TRADE_TUBE
	const SCGB_TRAINER_OR_MON_FRONTPIC_PALS
	const SCGB_MYSTERY_GIFT
	const SCGB_OPTIONS_MENU
	const SCGB_BETA_POKEGEAR_RADIO_PALS
	const SCGB_1E
	const SCGB_POKEDEX_5X5

SCGB_PARTY_MENU_HP_PALS  EQU -4
SCGB_RAM EQU -1

; PredefPals indexes (see gfx/sgb/predef.pal)
; GetPredefPal arguments (see engine/gfx/color.asm)
	const_def
	const PREDEFPAL_ROUTES
	const PREDEFPAL_KOBAN
	const PREDEFPAL_VIRIDIAN
	const PREDEFPAL_KUME
	const PREDEFPAL_NAGO
	const PREDEFPAL_LAVENDER; sgb super game boy morning
	const PREDEFPAL_AMAMI
	const PREDEFPAL_KANTO
	const PREDEFPAL_STAND
	const PREDEFPAL_FROSTPOINT
	const PREDEFPAL_RYUKYU
	const PREDEFPAL_MOUNT_FUJI
	const PREDEFPAL_SILENT
	const PREDEFPAL_CROWN
	const PREDEFPAL_PAGOTA
	const PREDEFPAL_BIRDON
	const PREDEFPAL_WESTPORT
	const PREDEFPAL_TEKNOS
	const PREDEFPAL_ALLOY
	const PREDEFPAL_SUNPOINT
	const PREDEFPAL_SANSKRIT
	const PREDEFPAL_BLUE_FOREST
	const PREDEFPAL_KIKAI_VILLAGE
	const PREDEFPAL_SILVER_CAVE
	const PREDEFPAL_DUNGEONS
	const PREDEFPAL_NITE
	const PREDEFPAL_BLACKOUT
	const PREDEFPAL_DIPLOMA ; RB_MEWMON
	const PREDEFPAL_TRADE_TUBE ; RB_BLUEMON
	const PREDEFPAL_POKEDEX ; RB_REDMON
	const PREDEFPAL_RB_CYANMON
	const PREDEFPAL_RB_PURPLEMON
	const PREDEFPAL_RB_BROWNMON
	const PREDEFPAL_RB_GREENMON
	const PREDEFPAL_RB_PINKMON
	const PREDEFPAL_RB_YELLOWMON
	const PREDEFPAL_CGB_BADGE ; RB_GREYMON
	const PREDEFPAL_BETA_SHINY_MEWMON
	const PREDEFPAL_BETA_SHINY_BLUEMON
	const PREDEFPAL_BETA_SHINY_REDMON
	const PREDEFPAL_BETA_SHINY_CYANMON
	const PREDEFPAL_BETA_SHINY_PURPLEMON
	const PREDEFPAL_BETA_SHINY_BROWNMON
	const PREDEFPAL_BETA_SHINY_GREENMON
	const PREDEFPAL_BETA_SHINY_PINKMON
	const PREDEFPAL_BETA_SHINY_YELLOWMON
	const PREDEFPAL_PARTY_ICON ; BETA_SHINY_GREYMON
	const PREDEFPAL_HP_GREEN
	const PREDEFPAL_HP_YELLOW
	const PREDEFPAL_HP_RED
	const PREDEFPAL_POKEGEAR
	const PREDEFPAL_BETA_LOGO_1
	const PREDEFPAL_BETA_LOGO_2
	const PREDEFPAL_GS_INTRO_GAMEFREAK_LOGO
	const PREDEFPAL_GS_INTRO_SHELLDER_LAPRAS
	const PREDEFPAL_BETA_INTRO_LAPRAS
	const PREDEFPAL_GS_INTRO_JIGGLYPUFF_PIKACHU_BG
	const PREDEFPAL_GS_INTRO_JIGGLYPUFF_PIKACHU_OB
	const PREDEFPAL_GS_INTRO_STARTERS_TRANSITION
	const PREDEFPAL_PACK_YELLOWRED
	const PREDEFPAL_PACK ; GS_INTRO_CHARIZARD
	const PREDEFPAL_SLOT_MACHINE_0
	const PREDEFPAL_SLOT_MACHINE_1
	const PREDEFPAL_SLOT_MACHINE_2
	const PREDEFPAL_SLOT_MACHINE_3
	const PREDEFPAL_BETA_POKER_0
	const PREDEFPAL_BETA_POKER_1
	const PREDEFPAL_BETA_POKER_2
	const PREDEFPAL_BETA_POKER_3
	const PREDEFPAL_BETA_RADIO
	const PREDEFPAL_BETA_POKEGEAR
	const PREDEFPAL_PACK_BLUEGREEN
	const PREDEFPAL_GS_TITLE_SCREEN_0
	const PREDEFPAL_GS_TITLE_SCREEN_1
	const PREDEFPAL_GS_TITLE_SCREEN_2
	const PREDEFPAL_GS_TITLE_SCREEN_3
	const PREDEFPAL_UNOWN_PUZZLE
	const PREDEFPAL_GAMEFREAK_LOGO_OB
	const PREDEFPAL_GAMEFREAK_LOGO_BG
	const PREDEFPAL_HILLS

; SGB system command codes
; http://gbdev.gg8.se/wiki/articles/SGB_Functions#SGB_System_Command_Table
	const_def
	const SGB_PAL01
	const SGB_PAL23
	const SGB_PAL03
	const SGB_PAL12
	const SGB_ATTR_BLK
	const SGB_ATTR_LIN
	const SGB_ATTR_DIV
	const SGB_ATTR_CHR
	const SGB_SOUND
	const SGB_SOU_TRN
	const SGB_PAL_SET
	const SGB_PAL_TRN
	const SGB_ATRC_EN
	const SGB_TEST_EN
	const SGB_ICON_EN
	const SGB_DATA_SND
	const SGB_DATA_TRN
	const SGB_MLT_REG
	const SGB_JUMP
	const SGB_CHR_TRN
	const SGB_PCT_TRN
	const SGB_ATTR_TRN
	const SGB_ATTR_SET
	const SGB_MASK_EN
	const SGB_OBJ_TRN

PALPACKET_LENGTH EQU $10
