Cries:
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Fearow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Kolta
	dba Cry_Hoothoot
	dba Cry_Burgela
	dba Cry_Slowking
	dba Cry_Cubburn
	dba Cry_Chikorita
	dba Cry_Palssio
	dba Cry_Mimmeo
	dba Cry_Cleffa
	dba Cry_Coinpur
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Angore
	dba Cry_Mantine
	dba Cry_Bruinus
	dba Cry_Natu
	dba Cry_Qwilfish
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Luxwan
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Paraspor
	dba Cry_Donphan
