; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_TropicalIslandJungle
	dba Music_Route117
	dba Music_UrasoeTrail
	dba Music_MagnetTrain
	dba Music_SWIslandsGymBattle
	dba Music_SWIslandsTrainerBattle
	dba Music_SWIslandsWildBattle
	dba Music_PokemonCenter
	dba Music_LookHiker
	dba Music_LookLass
	dba Music_LookOfficer
	dba Music_HealPokemon
	dba Music_LavenderTown
	dba Music_Route116
	dba Music_MtMoon
	dba Music_ShowMeAround
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_HallOfFame
	dba Music_IejimaTown
	dba Music_KantoRegion
	dba Music_TrainerVictory
	dba Music_WildPokemonVictory
	dba Music_GymLeaderVictory
	dba Music_MtMoonSquare
	dba Music_Gym
	dba Music_KobanIsland
	dba Music_ProfOaksPokemonTalk
	dba Music_ProfOak
	dba Music_LookRival
	dba Music_AfterTheRivalFight
	dba Music_Surf
	dba Music_Evolution
	dba Music_NationalPark
	dba Music_Credits
	dba Music_BirdonTown
	dba Music_CrownCity
	dba Music_LookKimonoGirl
	dba Music_UnionCave
	dba Music_NihonWildBattle
	dba Music_NihonTrainerBattle
	dba Music_Route105
	dba Music_TeknosCity
	dba Music_PagotaCity
	dba Music_NihonGymBattle
	dba Music_ChampionBattle
	dba Music_RivalBattle
	dba Music_RocketBattle
	dba Music_OakLabBackRoom
	dba Music_DarkCave
	dba Music_Route101
	dba Music_Route102
	dba Music_SSAqua
	dba Music_LookYoungster
	dba Music_LookBeauty
	dba Music_LookRocket
	dba Music_LookPokemaniac
	dba Music_LookSage
	dba Music_SilentTown
	dba Music_WestportCity
	dba Music_AmamiTown
	dba Music_PokemonChannel
	dba Music_PokeFluteChannel
	dba Music_TinTower
	dba Music_FiveFloorTower
	dba Music_BurnedTower
	dba Music_Lighthouse
	dba Music_KikaiVillage
	dba Music_MountFuji
	dba Music_SilentHills
	dba Music_RocketHideout
	dba Music_DragonsDen
	dba Music_NihonWildBattleNight
	dba Music_SanskritRuinsRadio
	dba Music_SuccessfulCapture
	dba Music_RouteU6U
	dba Music_Mom
	dba Music_MtFujiInteriorLower
	dba Music_PokemonLullaby
	dba Music_PokemonMarch
	dba Music_GoldSilverOpening
	dba Music_GoldSilverOpening2
	dba Music_MainMenu
	dba Music_SanskritRuinsInterior
	dba Music_RocketTheme
	dba Music_DancingHall
	dba Music_ContestResults
	dba Music_BugCatchingContest
	dba Music_KikaiVillageRocketRadio
	dba Music_Printer
	dba Music_PostCredits
	dba Music_SurfingPikachu
