	const_def
	const PAL_TOWNMAP_BORDER   ; 0
	const PAL_TOWNMAP_EARTH    ; 1
	const PAL_TOWNMAP_MOUNTAIN ; 2
	const PAL_TOWNMAP_CITY     ; 3
	const PAL_TOWNMAP_POI      ; 4
	const PAL_TOWNMAP_POI_MTN  ; 5

townmappals: MACRO
rept _NARG / 2
	dn PAL_TOWNMAP_\2, PAL_TOWNMAP_\1
	shift 2
endr
ENDM

; gfx/pokegear/town_map.png
	townmappals EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH
	townmappals EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH
	townmappals EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH
	townmappals EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH
	townmappals EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH
	townmappals EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH,   EARTH
; gfx/pokegear/pokegear.png
	townmappals MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN
	townmappals MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
	townmappals MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN,   MOUNTAIN
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
	townmappals BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER,   BORDER
