	object_const_def ; object_event constants
	const HYDROBIKER1
	const HYDROBIKER2
	const HYDROBIKER3
	const HYDROBIKER4
	const HYDROBIKER5
	const HYDROBIKER6
	const HYDROBIKER7
	const HYDROBIKER8
	const HYDROBIKER9
	const HYDROEMPLOYEE1
	const HYDROEMPLOYEE2
	const HYDROEMPLOYEE3
	const HYDROEMPLOYEE4
	const HYDROEMPLOYEE5

HydroPlant_MapScripts:
	db 0 ; scene scripts

	db 0 ; callbacks


TrainerBikerKazu:
	trainer BIKER, KAZU, EVENT_BEAT_BIKER_KAZU, BikerKazuSeenText, BikerKazuBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerKazuAfterBattleText
	waitbutton
	closetext
	end
	

TrainerBikerBenny:
	trainer BIKER, BENNY, EVENT_BEAT_BIKER_BENNY, BikerBennySeenText, BikerBennyBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerBennyAfterBattleText
	waitbutton
	closetext
	end
	
TrainerBikerDwayne:
	trainer BIKER, DWAYNE, EVENT_BEAT_BIKER_DWAYNE, BikerDwayneSeenText, BikerDwayneBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerDwayneAfterBattleText
	waitbutton
	closetext
	end


TrainerBikerHarris:
	trainer BIKER, HARRIS, EVENT_BEAT_BIKER_HARRIS, BikerHarrisSeenText, BikerHarrisBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerHarrisAfterBattleText
	waitbutton
	closetext
	end
	

TrainerBikerZeke:
	trainer BIKER, ZEKE, EVENT_BEAT_BIKER_ZEKE, BikerZekeSeenText, BikerZekeBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerZekeAfterBattleText
	waitbutton
	closetext
	end
	

TrainerBikerCharles:
	trainer BIKER, CHARLES, EVENT_BEAT_BIKER_CHARLES, BikerCharlesSeenText, BikerCharlesBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerCharlesAfterBattleText
	waitbutton
	closetext
	end
	

TrainerBikerRiley:
	trainer BIKER, RILEY, EVENT_BEAT_BIKER_RILEY, BikerRileySeenText, BikerRileyBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerRileyAfterBattleText
	waitbutton
	closetext
	end


TrainerBikerJoel:
	trainer BIKER, JOEL, EVENT_BEAT_BIKER_JOEL, BikerJoelSeenText, BikerJoelBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerJoelAfterBattleText
	waitbutton
	closetext
	end
	

TrainerBikerGlenn:
	trainer BIKER, GLENN, EVENT_BEAT_BIKER_GLENN, BikerGlennSeenText, BikerGlennBeatenText, 0, .Script

.Script:
	endifjustbattled
	opentext
	writetext BikerGlennAfterBattleText
	waitbutton
	closetext
	end
	
HydroPlantLassScript:
	jumptextfaceplayer HydroPlantLassText

HydroPlantGentlemanScript:
	jumptextfaceplayer HydroPlantGentlemanText

HydroPlantGentlenman2Script:
	jumptextfaceplayer HydroPlantGentlenman2Text

HydroPlantRockerScript:
	jumptextfaceplayer HydroPlantRockerText
	

HydroPlantTeacherScript:
	jumptextfaceplayer HydroPlantTeacherText
	
HydroPlantNugget:
	hiddenitem NUGGET, EVENT_HYDRO_PLANT_NUGGET
	
HydroPlantTeacherText:
	text "Oh, hello!"
	para "You helped get rid"
	line "of those BIKERS,"
	cont "right?"
	para "Thank you so very"
	line "much!"
	done

HydroPlantRockerText:
	text "I can't wait to"
	line "tell my friends"
	para "about what hap-"
	line "pened at work"
	cont "today!"
	done
	
HydroPlantGentlenman2Text:
	text "There was no way"
	line "to get work done"
	para "with those BIKERS"
	line "making all that"
	cont "noise!"
	done
	
HydroPlantGentlemanText:
	text "Well now, work"
	line "has certainly been"
	cont "interesting!"
	done
	
HydroPlantLassText:
	text "The power that's"
	line "generated by this"
	para "PLANT supplies all"
	line "of the SOUTHWEST"
	cont "ISLANDS!"
	done

BikerRileySeenText:
	text "Do you work here?"
	done
BikerRileyBeatenText:
	text "I'm fired!"
	done
	
BikerRileyAfterBattleText:
	text "I think we finally"
	line "scared all of the"
	cont "employees away!"
	done
	

BikerCharlesSeenText:
	text "Come to stop our"
	line "fun?"
	done
	
BikerCharlesBeatenText:
	text "Losing is lame!"
	done
	
BikerCharlesAfterBattleText:
	text "All we want to do"
	line "is ride!"
	done

BikerHarrisSeenText:
	text "What's our big"
	line "plan here?"
	para "Nothing, really."
	para "We're just having"
	line "fun!"
	done 
	
BikerHarrisBeatenText:
	text "Fun over!"
	done
	
BikerHarrisAfterBattleText:
	text "No one cares if"
	line "the water dries up"
	cont "for a bit, right?"
	done

BikerDwayneSeenText:
	text "You know any good"
	line "places to ride?"
	done
BikerDwayneBeatenText:
	text "Stopped in my"
	line "tracks!"
	done
	
BikerDwayneAfterBattleText:
	text "I might go ride in"
	line "IEJIMA TOWN with"
	cont "the others."
	done

BikerKazuSeenText:
	text "We are NIHON's"
	line "Island Bikers!"
	para "What, you've never"
	line "heard of us?"
	done
	
BikerKazuBeatenText:
	text "Island Biker down!"
	done
	
BikerKazuAfterBattleText:
	text "Yeah, I can't get"
	line "the name to catch"
	para "on, even with my"
	line "friends."
	done

BikerBennySeenText:
	text "No room here for"
	line "squares!"
	done
	
BikerBennyBeatenText:
	text "Okay, that was"
	line "good."
	done
	
BikerBennyAfterBattleText:
	text "Anyone who beats"
	line "me at #MON"
	para "can't be too much"
	line "of a square."
	done
	
BikerZekeSeenText:
	text "You think the cops"
	line "will show up soon"
	cont "and kick us out?"
	done
	
BikerZekeBeatenText:
	text "Are you a cop?"
	done
	
BikerZekeAfterBattleText:
	text "I bet my mom would"
	line "be upset with me"
	para "if I got in"
	line "trouble with the"
	cont "law."
	done
	
BikerJoelSeenText:
	text "No one can tell us"
	line "BIKERS what we can"
	cont "or can't do!"
	done
	
BikerJoelBeatenText:
	text "I guess I can't"
	line "beat you in a"
	cont "battle."
	done
	
BikerJoelAfterBattleText:
	text "Psh, whatever!"
	para "I'll just keep on"
	line "riding!"
	done


BikerGlennSeenText:
	text "Where are the"
	line "cops?"
	para "Have we scared"
	line "them off, too?"
	done
	
BikerGlennBeatenText:
	text "You're not scared!"
	done
	
BikerGlennAfterBattleText:
	text "Don't let them"
	line "know we're here,"
	cont "okay?"
	done
	

HydroPlant_MapEvents:
	db 0, 0 ; filler

	db 28 ; warp events
	warp_event 18, 35, WEATHERED_TRAIL, 1
	warp_event 19, 35, WEATHERED_TRAIL, 2
	warp_event 29,  0, HYDRAULIC_CAVE, 1
	warp_event 30,  0, HYDRAULIC_CAVE, 1
	warp_event  5, 30, HYDRO_PLANT, 6
	warp_event  9, 31, HYDRO_PLANT, 5
	warp_event  9, 28, HYDRO_PLANT, 8
	warp_event 35,  2, HYDRO_PLANT, 7
	warp_event 13, 28, HYDRO_PLANT, 10
	warp_event 37, 11, HYDRO_PLANT, 9
	warp_event 19, 30, HYDRO_PLANT, 12
	warp_event  5, 27, HYDRO_PLANT, 11
	warp_event  3, 26, HYDRO_PLANT, 14
	warp_event  5,  2, HYDRO_PLANT, 13
	warp_event  3, 21, HYDRO_PLANT, 16
	warp_event 37, 29, HYDRO_PLANT, 15
	warp_event 33, 33, HYDRO_PLANT, 18
	warp_event 11, 20, HYDRO_PLANT, 17
	warp_event  3, 15, HYDRO_PLANT, 20
	warp_event 27, 32, HYDRO_PLANT, 19
	warp_event 13,  7, HYDRO_PLANT, 22
	warp_event 29,  8, HYDRO_PLANT, 21
	warp_event 11, 16, HYDRO_PLANT, 24
	warp_event 37, 23, HYDRO_PLANT, 23
	warp_event 15, 14, HYDRO_PLANT, 26
	warp_event  9,  2, HYDRO_PLANT, 25
	warp_event 29,  3, HYDRO_PLANT, 28
	warp_event 15, 35, HYDRO_PLANT, 27
	
	db 0 ; coord events

	db 1 ; bg events
	bg_event 20,  8, BGEVENT_ITEM, HydroPlantNugget

	db 14 ; object events
	object_event 11, 33, SPRITE_BIKER, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_RED, OBJECTTYPE_TRAINER, 1, TrainerBikerBenny, EVENT_IEJIMA_TOWN_FIXED
	object_event 30, 16, SPRITE_BIKER, SPRITEMOVEDATA_SPINRANDOM_FAST, 0, 0, -1, -1, PAL_NPC_ORANGE, OBJECTTYPE_TRAINER, 3, TrainerBikerKazu, EVENT_IEJIMA_TOWN_FIXED
	object_event  8,  9, SPRITE_BIKER, SPRITEMOVEDATA_STANDING_RIGHT, 0, 0, -1, -1, PAL_NPC_BLUE, OBJECTTYPE_TRAINER, 4, TrainerBikerDwayne, EVENT_IEJIMA_TOWN_FIXED
	object_event 10, 30, SPRITE_BIKER, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_TRAINER, 2, TrainerBikerHarris, EVENT_IEJIMA_TOWN_FIXED
	object_event 27,  1, SPRITE_BIKER, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_BROWN, OBJECTTYPE_TRAINER, 3, TrainerBikerZeke, EVENT_IEJIMA_TOWN_FIXED
	object_event 19, 18, SPRITE_BIKER, SPRITEMOVEDATA_SPINRANDOM_FAST, 0, 0, -1, -1, PAL_NPC_GRAY, OBJECTTYPE_TRAINER, 3, TrainerBikerCharles, EVENT_IEJIMA_TOWN_FIXED
	object_event 23, 31, SPRITE_BIKER, SPRITEMOVEDATA_STANDING_UP, 0, 0, -1, -1, PAL_NPC_PINK, OBJECTTYPE_TRAINER, 4, TrainerBikerRiley, EVENT_IEJIMA_TOWN_FIXED
	object_event 36,  3, SPRITE_BIKER, SPRITEMOVEDATA_SPINRANDOM_FAST, 0, 0, -1, -1, PAL_NPC_YELLOW, OBJECTTYPE_TRAINER, 4, TrainerBikerJoel, EVENT_IEJIMA_TOWN_FIXED
	object_event  7, 20, SPRITE_BIKER, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_ORANGE, OBJECTTYPE_TRAINER, 4, TrainerBikerGlenn, EVENT_IEJIMA_TOWN_FIXED
	object_event 10, 12, SPRITE_LASS, SPRITEMOVEDATA_STANDING_LEFT, 1, 1, -1, -1, PAL_NPC_PINK, OBJECTTYPE_SCRIPT, 0, HydroPlantLassScript, EVENT_IEJIMA_TOWN_NOT_FIXED
	object_event  3,  2, SPRITE_TEACHER, SPRITEMOVEDATA_STANDING_UP, 1, 1, -1, -1, PAL_NPC_ORANGE, OBJECTTYPE_SCRIPT, 0, HydroPlantTeacherScript, EVENT_IEJIMA_TOWN_NOT_FIXED
	object_event 31, 29, SPRITE_GENTLEMAN, SPRITEMOVEDATA_STANDING_DOWN, 1, 1, -1, -1, PAL_NPC_BROWN, OBJECTTYPE_SCRIPT, 0, HydroPlantGentlemanScript, EVENT_IEJIMA_TOWN_NOT_FIXED
	object_event 21, 19, SPRITE_ROCKER, SPRITEMOVEDATA_STANDING_RIGHT, 1, 1, -1, -1, PAL_NPC_GREEN, OBJECTTYPE_SCRIPT, 0, HydroPlantRockerScript, EVENT_IEJIMA_TOWN_NOT_FIXED
	object_event 24, 16, SPRITE_GENTLEMAN, SPRITEMOVEDATA_STANDING_LEFT, 1, 1, -1, -1, PAL_NPC_GRAY, OBJECTTYPE_SCRIPT, 0, HydroPlantGentlenman2Script, EVENT_IEJIMA_TOWN_NOT_FIXED
