BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw HappaBitmasks
	dw BlossomoleBitmasks
	dw BlossomiteBitmasks
	dw FlambearBitmasks
	dw VolbearBitmasks
	dw DynabearBitmasks
	dw CruiseBitmasks
	dw AqualloBitmasks
	dw AquariusBitmasks
	dw TangBitmasks
	dw GelaniaBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw KotoraBitmasks
	dw RaitoraBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw PonittleBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw BomsealBitmasks
	dw BipetalBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw KingoldBitmasks
	dw SunfloraBitmasks
	dw OsunfishBitmasks
	dw AnchorageBitmasks
	dw GrotessBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw TritalesBitmasks
	dw UnownBitmasks
	dw TwinzBitmasks
	dw GirafarigBitmasks
	dw TurbanBitmasks
	dw GrimbyBitmasks
	dw ParaBitmasks
	dw AnimonBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw QuagsireBitmasks
	dw PluckrossBitmasks
	dw ScizorBitmasks
	dw RinringBitmasks
	dw BellringBitmasks
	dw SneaselBitmasks
	dw QwilfishBitmasks
	dw NumbpuffBitmasks
	dw MeowsyBitmasks
	dw MadameBitmasks
	dw CurstrawBitmasks
	dw CurpanBitmasks
	dw GrowliteBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw BallerineBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw ChixBitmasks
	dw MiltankBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw WolfanBitmasks
	dw WarwolfBitmasks
	dw LickilordBitmasks
	dw BlisseyBitmasks
	dw HoOhBitmasks
	dw LeafeonBitmasks
